### ISSUE TITLE
Amplify push - Parameters: [Name, Id] do not exist in the template

### ISSUE THREAD

**Issue by dylan-westbury** [aws-amplify/amplify-cli#11491]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [x] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm -g

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

10.5.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

notifications
analytics

### Amplify Commands

push

### Describe the bug

When I run amplify push (even after amplify pull --restore) I get the error:
🛑 The following resources failed to deploy:
🛑 Resource is not in the state stackUpdateComplete

Closer inspection in cloudformation this error shows:

<img width="1588" alt="Screen Shot 2022-11-29 at 12 06 29 pm" src="https://user-images.githubusercontent.com/16129043/204413345-2728f5fb-1073-4aa5-a809-a0358655eb29.png">

Also to note, prior to error I checked out of this environment (dev) into prod. It asked me for the push notification credentials (APNS and FCM). After adding APNS key and FCM server key it immediately threw an error (and everything has gone south from there):

```
2022-11-28T10:59:24.027Z|error : Could not initialize categories for 'prod': Cannot read property 'Enabled' of undefined
ProjectInitFault: Could not initialize categories for 'prod': Cannot read property 'Enabled' of undefined
2022-11-28T11:00:29.784Z|info : amplify env core checkout prod 
```

Now when I try and `amplify env checkout prod` it shows me the error:

Could not initialize platform for 'prod': unexpected end of file

### Expected behavior

amplify push should work

### Reproduction steps

1. amplify pull --restore
1. amplify push --force

### GraphQL schema(s)

Files were too long to post, uploaded to Google Drive: 

https://drive.google.com/drive/folders/1fWhItXjC4c4YUlg2hSaZdnlZpnZK9su7?usp=sharing

### Project Identifier

4f9361a8baa9127adefa33eadb05a3d8

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

`team-provider-info.json`

```
 "dev": {
...
    "categories": {
      "notifications": {
        "Pinpoint": {
          "Name": "Pinpoint-dev",
          "Id": "xxxxxxxxx",
          "Region": "us-east-1"
        }
      },
...
      "analytics": {
        "Pinpoint": {
          "Name": "Pinpoint-dev",
          "Id": "xxxxxxxxxx",
          "Region": "us-east-1"
        }
      }
    }
  },
```

**Comment by dylan-westbury** [comment]
I assume related https://github.com/aws-amplify/amplify-cli/issues/11376

Also originally I was facing this issue https://github.com/aws-amplify/amplify-cli/issues/5079#issuecomment-1284798986

**Comment by josefaidt** [comment]
Hey @dylan-westbury :wave: thanks for raising this! It appears this is somewhat related to #11376 , which the PR to fix that issue has been merged and is awaiting release. I will take a further look at this one to be sure that PR addresses this issue as well 🙂

**Comment by dylan-westbury** [comment]
Hi @josefaidt, thank you for the update. Do you have a rough ETA for release? Just right now we can't make updates to dev or prod backend environments and we need to push a release, unless there is a way I can pull a version with the merged updates?

**Comment by dylan-westbury** [comment]
Hi @josefaidt 

Is there any update here or a work around? We really need to get this release out as we have been blocked for a while.

Still facing the issue with the latest cli version 10.5.2

Thank you

![Screen Shot 2023-01-04 at 10 29 13 am](https://user-images.githubusercontent.com/16129043/210458429-8b03ce0d-a1a3-40de-b763-64388c8f7d1d.png)

**Comment by dylan-westbury** [comment]
Also just tried 10.6.0 

Steps:
1. Delete amplify directory 
2. amplify pull --appId d2h4pood8ci41s --envName dev
3. Amplify push --force (error occurs)

![Screen Shot 2023-01-04 at 11 22 46 am](https://user-images.githubusercontent.com/16129043/210462866-16836b01-a486-4157-a8cf-09666105f512.png)

**Comment by josefaidt** [comment]
Hey @dylan-westbury :wave: apologies for the delay here! While the original error is now fixed I was able to create a project and inspect the results:

1. `amplify init -y`
2. `amplify add notification` > FCM > enter API key
3. successful

however in the update flow I am presented with the same error noted in the original post

1. `amplify update analytics`
2. "Do you want to disable the FCM channel" no
3. observe error

```
✔ The FCM channel has been successfully updated.
🛑 Cannot read property 'Enabled' of undefined

907e6fb585c8641ae9249f42925db3df

**Comment by dylan-westbury** [comment]
Hi @josefaidt 

Thank you for your response. 

Yes the `amplify/backend/amplify-meta.json` file contains:

```
"notifications": {
    "Pinpoint": {
      "Id": "81aaac17dfea440293b1db3b6bd7c86e",
      "ResourceName": "Pinpoint",
      "Name": "Pinpoint-dev",
      "service": "Pinpoint",
      "output": {
        "Id": "81aaac17dfea440293b1db3b6bd7c86e",
        "Name": "Pinpoint-dev",
        "Region": "us-east-1",
        "APNS": {
          "ApplicationId": "81aaac17dfea440293b1db3b6bd7c86e",
          "CreationDate": "2022-11-08T20:33:31.821Z",
          "DefaultAuthenticationMethod": "Key",
          "Enabled": true,
          "HasCredential": false,
          "HasTokenKey": true,
          "Id": "apns",
          "IsArchived": false,
          "LastModifiedDate": "2022-11-08T20:33:31.821Z",
          "Platform": "APNS",
          "Version": 1
        },
        "FCM": {
          "ApplicationId": "81aaac17dfea440293b1db3b6bd7c86e",
          "CreationDate": "2022-11-08T20:30:39.467Z",
          "Enabled": true,
          "HasCredential": true,
          "Id": "gcm",
          "IsArchived": false,
          "LastModifiedDate": "2022-11-08T20:30:39.467Z",
          "Platform": "GCM",
          "Version": 1
        },
        "Email": {
          "ApplicationId": "81aaac17dfea440293b1db3b6bd7c86e",
          "CreationDate": "2022-11-09T12:16:49.945Z",
          "Enabled": false,
          "FromAddress": "xxxxxx<xxxxx@xxxxxx.xxx.xx>",
          "Id": "email",
          "Identity": "arn:aws:ses:us-east-1:xxxxxxxxxx:identity/xxxxx@xxxxxx.xxx.xx",
          "IsArchived": false,
          "LastModifiedDate": "2022-11-29T03:23:09.709Z",
          "MessagesPerSecond": 14,
          "Platform": "EMAIL",
          "Version": 6
        },
        "regulatedResourceName": "Pinpoint"
      },
      "lastPushTimeStamp": "2023-01-03T23:47:21.552Z"
    }
  },
```

Additionally the same for analytics in the file
```
  "analytics": {
    "Pinpoint": {
      "providerPlugin": "awscloudformation",
      "service": "Pinpoint",
      "output": {
        "appName": "Pinpoint-dev",
        "Region": "us-east-1",
        "Id": "81aaac17dfea440293b1db3b6bd7c86e"
      },
      "lastPushTimeStamp": "2023-01-04T00:21:57.673Z",
      "providerMetadata": {
        "s3TemplateURL": "https://s3.amazonaws.com/amplify-template-dev-xxxxx-deployment/amplify-cfn-templates/analytics/pinpoint-cloudformation-template.json",
        "logicalId": "analyticsPinpoint"
      }
    }
  },
```

**Comment by dylan-westbury** [comment]
I tried to remove notifications and push because we need to release, now facing this error when pushing `error : Failed to extract zip file`
```
ZipExtractFault: Failed to extract zip file: 
2023-01-18T05:22:54.311Z|info : amplify push core  
2023-01-18T05:22:54.372Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-18T05:22:55.321Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:22:55.322Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:22:55.322Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:22:55.330Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:22:55.331Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:22:55.331Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:22:55.335Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2023-01-18T05:22:55.337Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]late-[***]ev-[***]208-[***]ment"}])
2023-01-18T05:23:07.081Z|info : amplify pull core  {"restore":true,"yes":false}
2023-01-18T05:23:07.128Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-18T05:35:05.635Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:35:05.638Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:35:05.638Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:35:05.649Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:35:05.650Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:35:05.650Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:35:05.655Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2023-01-18T05:35:05.658Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]late-[***]ev-[***]208-[***]ment"}])
2023-01-18T05:35:09.760Z|error : Failed to extract zip file: 
ZipExtractFault: Failed to extract zip file: 
2023-01-18T05:39:06.946Z|info : amplify status core  {"yes":false}
2023-01-18T05:39:07.005Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-18T05:39:08.480Z|info : amplify-provider-awscloudformation.display-helpful-urls.showCognitoSandBoxMessage(["TemplateAuth"])
2023-01-18T05:39:21.770Z|info : amplify pull core  
2023-01-18T05:39:21.816Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-18T05:39:31.113Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:39:31.114Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:39:31.115Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:39:31.123Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:39:31.123Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:39:31.123Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:39:31.128Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2023-01-18T05:39:31.130Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]late-[***]ev-[***]208-[***]ment"}])
2023-01-18T05:39:35.344Z|error : Failed to extract zip file: 
ZipExtractFault: Failed to extract zip file: 
```

Because of that strange error, I erased the amplify directories and tried a fresh pull using `amplify pull --appId d2h4pood8ci41s --envName dev` but now facing this error message: `error : Failed to pull the backend`

```
2023-01-18T05:44:30.312Z|info : amplify pull core  {"appId":"[***]8ci41s","envName":"[***]ev","yes":false}
2023-01-18T05:44:30.357Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-18T05:44:36.015Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:44:36.018Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:44:36.018Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:44:36.030Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2023-01-18T05:44:36.421Z|info : amplify-provider-awscloudformation.attach-backend.getAmplifyApp.amplifyClient.getApp([{"appId":"[***]8ci41s"}])
2023-01-18T05:44:36.727Z|info : amplify-provider-awscloudformation.attach-backend.getBackendEnv.amplifyClient.getBackendEnvironment([{"appId":"[***]8ci41s","environmentName":"[***]ev"}])
2023-01-18T05:44:37.516Z|info : amplify-provider-awscloudformation.attach-backend.downloadBackend.s3.getObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]late-[***]ev-[***]208-[***]ment"}])
2023-01-18T05:44:41.727Z|error : Failed to pull the backend.
PullBackendFault: Failed to pull the backend.
2023-01-18T05:47:05.596Z|info : amplify pull core  {"appId":"[***]8ci41s","envName":"[***]ev","yes":false}
2023-01-18T05:47:05.641Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-18T05:47:21.445Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["dylan-storymatch"])
2023-01-18T05:47:21.449Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-01-18T05:47:21.450Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["dylan-storymatch"])
2023-01-18T05:47:21.464Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2023-01-18T05:47:22.052Z|info : amplify-provider-awscloudformation.attach-backend.getAmplifyApp.amplifyClient.getApp([{"appId":"[***]8ci41s"}])
2023-01-18T05:47:22.786Z|info : amplify-provider-awscloudformation.attach-backend.getBackendEnv.amplifyClient.getBackendEnvironment([{"appId":"[***]8ci41s","environmentName":"[***]ev"}])
2023-01-18T05:47:23.180Z|info : amplify-provider-awscloudformation.attach-backend.downloadBackend.s3.getObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]late-[***]ev-[***]208-[***]ment"}])
2023-01-18T05:47:27.365Z|error : Failed to pull the backend.
PullBackendFault: Failed to pull the backend.
```

**Comment by dylan-westbury** [comment]
Hi @josefaidt 

We really need to get this release out before the end of the month as we have been blocked since November last year, including any updates / testing that we are unable to make currently.

 I cannot restore any environment (dev or prod), all I see is the error:

![Screenshot 2023-01-26 at 10 32 33 am](https://user-images.githubusercontent.com/16129043/214717206-d47caa7f-a75c-4866-a760-441c22c9cfa8.png)

Session Identifier: 94a89278-0cee-4c87-a228-2fca06a68a8d

When running:

`amplify pull --appId d2h4pood8ci41s --envName dev`
OR
`amplify pull --appId d2h4pood8ci41s --envName prod`


When running the same command on a lower version of amplify-cli, this following error shows:

![Screenshot 2023-01-26 at 10 40 28 am](https://user-images.githubusercontent.com/16129043/214718216-ea56427c-25b7-47e2-ad0b-0c1ddcbb2718.png)


My question is, **how can I restore the project?** Amplify pull is not working, is there another way?. I've tried pulling a fresh copy of the repo and going from there but I end up in the same position as above. 

![Screenshot 2023-01-26 at 10 37 55 am](https://user-images.githubusercontent.com/16129043/214717908-a9352cfa-73cc-406c-962c-db4b69c04d2b.png)

**Comment by josefaidt** [comment]
Hey @dylan-westbury :wave: apologies for the delay here! Hmm, my first instinct for the original issue is to patch the corresponding CloudFormation template with the appropriate parameters (`Name` and `Id`), however the zip extraction issue is concerning. Can you try downloading the `#current-cloud-backend.zip` archive from your project's deployment bucket and attempt unzipping it? Do you notice any files that seem out of place given the most recent action of removing the notifications?

**Comment by dylan-westbury** [comment]
Hi @josefaidt,

Yesterday I noticed the `#current-cloud-backend.zip` is corrupted for both environments, so I am in the process of replacing it in it's original state. 

For the original issue, where would I find the CloudFormation template with the missing `Name` and `Id`? To me it appears that this was correctly showing in my local project files. Perhaps it was missing in the `#current-cloud-backend.zip` or would that not be the case?

**Comment by josefaidt** [comment]
> For the original issue, where would I find the CloudFormation template with the missing Name and Id? 

This would be in `amplify/backend/analytics/<resource-name>/pinpoint-cloudformation-template.json`

![image](https://user-images.githubusercontent.com/5033303/215217139-ca19328f-43a4-4707-a965-ac5797fe2c35.png)

Did the Pinpoint resource already exist before the original failed push attempt? Do you remember what the final change was before pushing?

**Comment by dylan-westbury** [comment]
Hi @josefaidt 

Yes so Name and Id was there as you have shown in the CloudFormation template also.

When I did an amplify pull or push it asked for notification credentials which then just broke the environment.

However I have managed to resolve, firstly I had to fix the corrupted `#current-cloud-backend.zip` directory by using a free unzip app from the App Store as I couldn't unzip on a Mac. 

I unzipped the directory and zipped it back up with the same files, replaced the corrupted `#current-cloud-backend.zip` in the S3 deployment bucket for the env. 

I then removed notifications and analytics as well as any function dependencies on it. I also had to remove some DynamoDB streams that had the analytics category permissions as they started erroring on amplify push. After amplify push (or during can't remember) the `#current-cloud-backend.zip` corrupted again so I had to unzip and replace again. 

I haven't re-added notifications category yet because I assume I will have the same issues in the prod environment when I get to it where I will need to repeat the above.

**Comment by dylan-westbury** [comment]
Hi @josefaidt ,

Is there a way to re-create the `#current-cloud-backend.zip` directory. For our prod environment it seems completely corrupted 

<img width="799" alt="Screenshot 2023-02-03 at 7 03 59 am" src="https://user-images.githubusercontent.com/16129043/216437688-84feedcc-35dd-4244-89c2-9b51dfa2c8b9.png">

**Comment by josefaidt** [comment]
Hey @dylan-westbury you should be able to zip the local copy of current-cloud-backend and force push. Just to clarify when you are pushing, are you always pushing locally with the cli by running `amplify push`? Is it on subsequent pulls you notice the zip archive is corrupted?

**Comment by dylan-westbury** [comment]
Hi @josefaidt,

I was lucky enough to have a copy of the prod environment locally (not within the cloned repo) so I was able to restore the prod environment. 

Yes always `amplify push`. Whenever I did an `amplify pull` that fail message would always show. Then when I downloaded the zip it was noticeably corrupted.

**Comment by dylan-westbury** [comment]
I am facing the error again:

![Screenshot 2023-02-08 at 6 11 30 pm](https://user-images.githubusercontent.com/16129043/217459568-e037eda9-d878-4bf0-9252-d6e78c833709.png)

Steps to reproduce:
1. amplify analytics add (in dev env)
3. amplify push
4. amplify env checkout prod
5. amplify push

```
 "Outputs": {
    "Region": {
      "Value": {
        "Fn::FindInMap": [
          "RegionMapping",
          {
            "Ref": "AWS::Region"
          },
          "pinpointRegion"
        ]
      }
    },
    "Id": {
      "Value": {
        "Fn::If": [
          "ShouldCreatePinpointApp",
          {
            "Fn::GetAtt": [
              "PinpointFunctionOutputs",
              "Id"
            ]
          },
          {
            "Ref": "appId"
          }
        ]
      }
    },
    "appName": {
      "Value": {
        "Fn::If": [
          "ShouldCreatePinpointApp",
          {
            "Fn::GetAtt": [
              "PinpointFunctionOutputs",
              "Name"
            ]
          },
          {
            "Ref": "appName"
          }
        ]
      }
    }
  },
```

**Comment by dylan-westbury** [comment]
Furthermore something strange is happening. 

I have completely removed analytics and notifications, from both environments (so there is no trace including in team-provider-info.json, etc), amplify push --force etc. Then re-add analytics for both environments then as I check back into dev notifications is showing again. 
Steps to reproduce:

(In dev environment)
1. amplify notifications remove
2. amplify analytics remove
3. check no trace in amplify project 
4. amplify status
5. amplify push --force
6. amplify env checkout prod
7. repeat steps 1 to 4
8. amplify env checkout dev
9. amplify analytics add
10. amplify push
11. amplify checkout prod
12. amplify push
13. amplify checkout dev

At this step, notifications is showing again in the project (when I run `amplify status`). As I `amplify env checkout dev` it says something along the lines of initing apns etc. (can't recall exact message)

**Comment by dylan-westbury** [comment]
I resolved the above issue by continually removing pinpoint completely from the project and for all environments then re-adding, until any errors stopped showing and the pinpoint projects were re-created without issues.

However for another project amplify hosting fails on the backend step for older and latest versions of amplify CLI

Parameters: [authRoleArn, cloudWatchPolicyName, cloudformationPolicyName, unauthRoleName, appName, pinpointPolicyName, unauthPolicyName, authRoleName, roleName, authPolicyName] must have values

![Screenshot 2023-03-06 at 12 54 12 pm](https://user-images.githubusercontent.com/16129043/223002320-51066abf-7474-4712-89fa-a420f6fef284.png)

**Comment by josefaidt** [comment]
Hey @dylan-westbury this issue is now resolved in CLI v10.8.1, can you try upgrading to CLI v10.8.1?

**Comment by dylan-westbury** [comment]
I'm still getting the error in 11.0.3 after creating a new environment. 

<img width="1006" alt="Screenshot 2023-03-28 at 2 48 32 pm" src="https://user-images.githubusercontent.com/16129043/228123080-be274402-90cc-4738-8bc9-bbe96cd87127.png">
