### ISSUE TITLE
Amplify init fails with Cannot read property 'Id' of undefined

### ISSUE THREAD

**Issue by Krishnakumar-Santhanam** [aws-amplify/amplify-cli#12365]
### How did you install the Amplify CLI?

asdf

### If applicable, what version of Node.js are you using?

16.18.0

### Amplify CLI Version

10.8.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

We are using 2 git branches to deploy our backend changes to two different amplify environments, `master` for `testing` and `production` for `production`. 

We run amplify `init` `push` `pull` in headless mode in GitHub action CI/CD where we run `init` and `push` in the backend workflow and `pull` in the mobile workflow since we need `aws-exports.js` file to build our FE(mobile app). 

**We don't find any issues running these amplify commands for the `testing` environment from the `master` branch.**
However, when we run the exact same setup for the `production` branch and try to `init` amplify production we face the error - `Cannot read property 'Id' of undefined`. We follow GitHub's environment deployment feature to segregate our environmental secrets and have the below steps for production deployment.

1. git merge origin/master
2. Approve production deployment
3. Run backend workflow
4. Run mobile workflow

### Expected behavior

`Amplify init` runs successfully for the `production` environment followed by `amplify push`. We tried different amplify versions `10.3.2` `10.7.1` `11.0.0` but no luck.

### Reproduction steps

We are using a reusable action for all our branches to run amplify in headless mode

``` 
envName=${{ inputs.amplify-env-name }}
profileName=${{ inputs.aws-profile-name }}
AMPLIFY_APP_ID=${{ inputs.amplify-app-id }}

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"${profileName}\"\
}"

AMPLIFY="{\
\"envName\":\"${envName}\",\
\"defaultEditor\":\"code\"\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

echo "Initializing Amplify project for env: ${envName}"
amplify init --amplify $AMPLIFY --providers $PROVIDERS --yes```

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam :wave: thanks for raising this! While we begin to look at this in more depth, would you mind sending us the project ID output from `amplify diagnose --send-report`? Additionally, do you have analytics or notifications in your project?

**Comment by Krishnakumar-Santhanam** [comment]
>the project ID

7f07c16df38220edf6ec5b8a025dba88

Yeah @josefaidt we do use analytics and notifications in our project

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam thanks for sending that over and for clarifying! The description sounds familiar to https://github.com/aws-amplify/amplify-cli/issues/11719, where this issue was fixed with later versions of the CLI. Does your CI pipeline also use version 10.8.1?

**Comment by Krishnakumar-Santhanam** [comment]
Hey, @josefaidt yeah we are using version `10.8.1` in our pipeline and the still issue exists! We also tried different versions as mentioned earlier but no luck yet.

**Comment by Krishnakumar-Santhanam** [comment]
Hey, @josefaidt I just tried with `11.0.3` but no luck and I get the same error. 

>Do you have an email notification in your project?

Currently, we don't have it in Production yet but we will be adding them in a week or two. Currently, we use `analytics` and `notifications` in the `production` environment`.

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam what notifications do you use in your project?

**Comment by Krishnakumar-Santhanam** [comment]
Hey @josefaidt We use `Apple Push Notification Service (APNs)` and `Firebase Cloud Messaging (FCM)`

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam can you confirm whether your `production` environment contains the `Id` key for either analytics or notifications in the `amplify/team-provider-info.json` file?

```json
"categories": {
      "api": {
        "a12357": {}
      },
      "auth": {
        "a12357": {}
      },
      "analytics": {
        "a12357": {},
        "Pinpoint": {
          "Name": "a12357-dev",
          "Id": "c261445cfa244e58ae7fd40c4232edbb",
          "Region": "us-east-1"
        }
      },
      "notifications": {
        "Pinpoint": {
          "Name": "a12357-dev",
          "Id": "c261445cfa244e58ae7fd40c4232edbb",
          "Region": "us-east-1"
        }
      }
    }
```

**Comment by Krishnakumar-Santhanam** [comment]
Hey @josefaidt Yes, our `team-provider-info.json` file has an entry for the notifications section and `Id` is available.

```
"notifications": {
        "Pinpoint": {
          "Name": "[REDACTED]-production",
          "Id": "[REDACTED]",
          "Region": "eu-west-1"
        }
      },
 ```

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam thanks for checking on that! Does that value also exist for the Analytics resource? The values in both should match

**Comment by Krishnakumar-Santhanam** [comment]
Hey @josefaidt I don't see the `Id` for `analytics` and below is what I could see in `team-provider-info.json`

```
"analytics": {
        "[REDACTED]": {}
 }
```

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam can you try running `amplify env checkout <current-env-name>` on the latest version of the CLI to see if it patches it in for you? If not, can you manually copy/paste the parameters block from `notifications` inside `analytics` under `Pinpoint` (shown in my code snippet above)?

**Comment by Krishnakumar-Santhanam** [comment]
Hey @josefaidt I have manually copied the `notifications` block and added them inside `analytics` and did run `amplify push` and it succeeded. But when I try to run `amplify init` in the CI/CD pipeline I still have the same issue of `Cannot read property 'Id' of undefined`

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam can you confirm whether you see the following parameters in your project's `amplify/backend/backend-config.json` file? 

```json
"parameters": {
    "AMPLIFY_analytics_Pinpoint_Id": {
      "usedBy": [
        {
          "category": "analytics",
          "resourceName": "Pinpoint"
        }
      ]
    },
    "AMPLIFY_analytics_Pinpoint_Name": {
      "usedBy": [
        {
          "category": "analytics",
          "resourceName": "Pinpoint"
        }
      ]
    },
    "AMPLIFY_analytics_Pinpoint_Region": {
      "usedBy": [
        {
          "category": "analytics",
          "resourceName": "Pinpoint"
        }
      ]
    },
```

In an attempt to reproduce I've removed all references to the analytic's `Pinpoint` resource, pushed, and reinitialized afterwards but the parameters were repopulated in `team-provider-info.json`

**Comment by Krishnakumar-Santhanam** [comment]
> can you confirm whether you see the following parameters in your project's amplify/backend/backend-config.json file

Hey @josefaidt Yes, I could see them in the file.

**Comment by Krishnakumar-Santhanam** [comment]
Hey @josefaidt Let me know if any other files needed comparison. Also, if I try to do a clean pull of our `production` environment in a newly created repo locally I get the same error - `Cannot read property 'Id' of undefined`

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam when you manually copied the values was this done for all environments or only the affected `production` env? Would you be willing to share a zip archive of your `amplify/` directory or hop on a quick call to debug?

**Comment by Krishnakumar-Santhanam** [comment]
Hey @josefaidt I have copied the value only for the affected environment - `production`. We would like to hop on a quick call to debug the issue together.

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam awesome! Are you on our [community Discord server](https://discord.gg/invite/amplify)? If so, would you mind sending me a DM there? My username in the server is `josef`

Otherwise would you mind sending an email to amplify-cli@amazon.com to orchestrate?

**Comment by Krishnakumar-Santhanam** [comment]
Hey @josefaidt our error has been resolved now. Below are the things we have done recently after this issue was raised.

- The email category was added to our `production` Pinpoint application
- `amplify update notifications` was executed against the `production` environment

We don't face the error `Cannot read property 'Id' of undefined` in the pipeline and `amplify pull`/`amplify env checkout production` also works as expected.

Also, one more thing is even though we had `analytics` in our project it was showing as disabled in the console and after the above recent changes it is now showing as enabled and the `amplify-meta.json` file is also updated now with the below details and earlier it was empty.

```
"notifications": {
    "[REDACTED]": {
      "Id": "[REDACTED]",
      "ResourceName": "[REDACTED]",
      "Name": "[REDACTED]-production",
      "service": "Pinpoint",
      "output": {
        "Id": "[REDACTED]",
        "Name": "[REDACTED]-production",
        "Region": "eu-west-1",
        "APNS": {
          "ApplicationId": "[REDACTED]",
          "CreationDate": "2023-04-04T09:59:55.377Z",
          "DefaultAuthenticationMethod": "Certificate",
          "Enabled": true,
          "HasCredential": true,
          "HasTokenKey": false,
          "Id": "apns",
          "IsArchived": false,
          "LastModifiedDate": "2023-04-04T10:13:01.207Z",
          "Platform": "APNS",
          "Version": 2
        },
        "FCM": {
          "ApplicationId": "[REDACTED]",
          "CreationDate": "2023-04-04T10:02:37.024Z",
          "Enabled": true,
          "HasCredential": true,
          "Id": "gcm",
          "IsArchived": false,
          "LastModifiedDate": "2023-04-04T10:02:37.024Z",
          "Platform": "GCM",
          "Version": 1
        },
        "Email": {
          "ApplicationId": "[REDACTED]",
          "CreationDate": "2023-04-12T06:46:24.518Z",
          "Enabled": true,
          "FromAddress": "[REDACTED]",
          "Id": "email",
          "Identity": "[REDACTED]",
          "IsArchived": false,
          "LastModifiedDate": "2023-04-12T12:09:30.500Z",
          "MessagesPerSecond": 14,
          "Platform": "EMAIL",
          "Version": 3
        },
        "regulatedResourceName": "[REDACTED]"
      },
      "lastPushTimeStamp": "2023-04-19T08:05:47.725Z"
    }
  },
```

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam glad to hear you're back up and running, and thank you for posting your findings! It is certainly helpful! Given the issue is resolved I will close this for now, however if this resurfaces please reply back to this thread or create a new bug report so we can investigate further 🙂

**Comment by danielvouch** [comment]
We are still getting this error when looking to create a new environment - when will this be resolved?
