### ISSUE TITLE
Error Configuring on WSL

### ISSUE THREAD

**Issue by am-a** [aws-amplify/amplify-cli#1647]
**Describe the bug**
Using `amplify configure` on WSL without `cmd.exe` in your path will not work and throws an error which kills the process. I believe this is because the CLI is attempting to open the brower using the `opn` library @v5.3.0. 

**To Reproduce**
1. Ensure windows path is _not_ in available in WSL by editing wsl.conf in /etc/wsl.conf
```
[interop]
appendWindowsPath=false # append Windows path to $PATH variable; default is true
```
2. In WSL, install `@aws-amplify/cli` in a fresh (unconfigured) environment
3. The following error will appear:
```
Follow these steps to set up access to your AWS account:

Sign in to your AWS administrator account:
https://console.aws.amazon.com/
Press Enter to continue
2019-06-11T14:38:32.027Z - error: uncaughtException: spawn cmd.exe ENOENT date=Tue Jun 11 2019 14:38:30 GMT+0000 (GMT), pid=351, uid=1000, gid=1000, cwd=[redacted] execPath=/home/am-a/.nvm/versions/node/v10.16.0/bin/node, version=v10.16.0, argv=[/home/am-a/.nvm/versions/node/v10.16.0/bin/node, /home/am-a/.yarn/bin/amplify, configure], rss=118603776, heapTotal=95195136, heapUsed=69676128, external=3991707, loadavg=[0.5185546875, 0.57763671875, 0.5859375], uptime=929, trace=[column=19, file=internal/child_process.js, function=Process.ChildProcess._handle.onexit, line=240, method=onexit, native=false, column=16, file=internal/child_process.js, function=onErrorNT, line=415, method=null, native=false, column=19, file=internal/process/next_tick.js, function=process._tickCallback, line=63, method=_tickCallback, native=false, column=11, file=internal/modules/cjs/loader.js, function=Module.runMain, line=832, method=runMain, native=false, column=19, file=internal/bootstrap/node.js, function=startup, line=283, method=null, native=false, column=3, file=internal/bootstrap/node.js, function=bootstrapNodeJSCore, line=622, method=null, native=false], stack=[Error: spawn cmd.exe ENOENT,     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19),     at onErrorNT (internal/child_process.js:415:16),     at process._tickCallback (internal/process/next_tick.js:63:19),     at Function.Module.runMain (internal/modules/cjs/loader.js:832:11),     at startup (internal/bootstrap/node.js:283:19),     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)]
```

**Expected behavior**

The browser will open and the app will wait for the "enter" key to be pressed.

**Screenshots**

**Desktop (please complete the following information):**
```
OS: Ubuntu 18.04.2 LTS on Windows 10 x86_64
Kernel: 4.4.0-17134-Microsoft
Uptime: 22 mins
Packages: 522 (dpkg)
Shell: zsh 5.4.2
Terminal: /dev/tty1
CPU: Intel i7-6850K (12) @ 3.601GHz
Memory: 9072MiB / 32605MiB

```
**Additional context**
I believe this is linked a previous issue that was closed but never solved: https://github.com/aws-amplify/amplify-cli/issues/189

**Comment by yuth** [comment]
@am-a I could not reproduce this even after setting `appendWindowsPath` to `false`. Do you have any specific browser installed?

**Comment by am-a** [comment]
No specific browser - `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`;

Does running `cmd.exe` work from your command line within WSL? Does launching the browser work?

**Comment by am-a** [comment]
@yuth: 
```
npm install -g opn@5.3.0
node -e "opn = require('opn'); opn('http://foo.bar')"

(node:13956) UnhandledPromiseRejectionWarning: Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at evalScript (internal/bootstrap/node.js:592:13)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:13956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Looks like pretty much the same error

**Comment by am-a** [comment]
Probably could be resolved if this is fixed - I'll try to come up with a PR: https://github.com/sindresorhus/open/issues/106

**Comment by yuth** [comment]
This has been fixed in https://github.com/aws-amplify/amplify-cli/pull/1655

**Comment by andreialecu** [comment]
This bug still exists on WSL on CLI version 4.17.2

![image](https://user-images.githubusercontent.com/697707/78240538-d51df880-74e7-11ea-9a2f-3b4c5aac3ca0.png)

**Comment by andreialecu** [comment]
A workaround is to run `$ export PATH=$PATH:/c/Windows/System32` prior to running `amplify configure`
