### ISSUE TITLE
amplify cli 1.7.4 freezes when adding graphql api

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws-amplify/amplify-cli#1688]
**Describe the bug**
Amplify 1.7.4
Running `amplify add api` and then choosing GrahpQL freezes terminal. I cannot type a api name or kill the process.

**To Reproduce**
1. Go to project and run `amplify add api`
2. Choose Graphql
3. Try to type name...freezes

**Expected behavior**
I expect to be able to type the name

**Desktop (please complete the following information):**
 - OS: OSX 10.14.5
 -Terminal

**Extra context**
I was running 1.6.9 but any version new then that is having the same issue. I am going back to 1.6.9 and see what happen and maybe reboot my mac?

Update: even 1.6.9 now is freezing. Will try reboot first.
Issue not resolved. The CLI is hanging because some unknown reason.

**Comment by mattiLeBlanc** [comment]
I tried to do amplify configure, but when I am asked to add a user, the CLI is also frozen. Not sure what is going on here but it seems like it is waiting on a request from the AWS service which is maybe pending?

**Comment by nickchauhan** [comment]
Same is happening with me when I'm trying to add environment using Amplify CLI 1.7.4
```
amplify env add
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment
```
So when I try to enter the name of the environment it freezes

**Comment by nickchauhan** [comment]
Same is happening with me when I'm trying to add environment using Amplify CLI 1.7.4
```
amplify env add
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment
```
So when I try to enter the name of the environment it freezes

**Comment by Butler12** [comment]
I am seeing the same thing when running 'amplify configure' after updating to 1.7.4. It was working fine in 1.6.5. It is getting stuck after i select a 'region' during the configure steps.

Running on OSX 10.12.6 with iTerm2.

**Comment by mattiLeBlanc** [comment]
So when I run it on my private laptop, it doesn't freeze, so it is not my AWS username or anything like that. Also, I installed amplify yesterday and it is running at 1.7.4.
So it seems only the laptop where I upgraded from a 1.6.x to 1.7.4 did something irreversible.

**Comment by nfpreports** [comment]
> So when I run it on my private laptop, it doesn't freeze, so it is not my AWS username or anything like that. Also, I installed amplify yesterday and it is running at 1.7.4.
> So it seems only the laptop where I upgraded from a 1.6.x to 1.7.4 did something irreversible.

I'm having the same trouble - it worked fine 6 days ago when I was running through a tutorial. Tonight I go to set up a new project and 'amplify configure' askes for the region, then username and freezes :(

**Comment by mtg5014** [comment]
I get the same running ```amplify init``` on OSX 10.14.5 with Terminal.

**Comment by DevilsNightsix** [comment]
I'm also getting this during `amplify configure`, terminal hangs on 'Specify the username of the new IAM user:'

**Comment by praisegeek** [comment]
I can confirm that @aws-amplify/cli version 1.7.4 started freezing after the upgrade. It freezes after passing through any first command.

**Comment by daajack** [comment]
Same here with amplify configure/init (1.7.3 and 1.7.4). It stucks on the second question. The process can be killed from another console with kill -9 PROCESS_ID. I didn't found any error message.

**Comment by UnleashedMind** [comment]
we root-caused this issue and it is due to a bug in one of the dependencies 

https://github.com/SBoudrias/Inquirer.js/issues/811

we wil lock the version and roll out a fix soon

**Comment by damianrr** [comment]
FWIW: It's also happening with `amplify update function` and is also happening in versions: 1.7.3, 1.7.2 and 1.7.1

**Comment by UnleashedMind** [comment]
@damianrr 

It happens if there is a fresh installation of the inquirer package

**Comment by kaustavghosh06** [comment]
We've fixed this issue. Please install the latest version of the CLI (1.7.5)  which has this fix.

**Comment by mattiLeBlanc** [comment]
Thanks Amplify team for the quick fix!

**Comment by GIOkafor** [comment]
I am still experiencing this issue in the CLI version (1.8.2) @kaustavghosh06

**Comment by skatolyk** [comment]
Still happens on version @aws-amplify/cli@4.13.1

**Comment by ryudice** [comment]
It's happening to me as well

**Comment by wojtik8** [comment]
> It's happening to me as well, using version 4.17.1

Are you behind a corporate proxy? If so, this can be related to the Usage Data collection, which is being sent to the Internet each time you execute an amplify command. In my case opting out helped:

`amplify configure --usage-data-off`
