### ISSUE TITLE
amplifiy init freezing

### ISSUE THREAD

**Issue by goalguy10** [aws-amplify/amplify-cli#1705]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**

- I am trying to setup amplify for a project and when I run "amplify init" from the CLI it will freeze at the "Enter a name for the environment" phase. I get the flashing cursor but I am unable to type anything. Ctrl+c does nothing as well. The only way to get out of it is to close Terminal.

**To Reproduce**

- run amplify init

**Expected behavior**

- Allow me to enter a name for the environment.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Amplify CLI Version: 1.7.4

**Comment by sprucify** [comment]
I had freezing issues on version 1.7.4, fixed for me at version 1.7.5

**Comment by UnleashedMind** [comment]
@goalguy10 

There was an issue with one of the dependency packages in 1.7.4. We've fixed it in our last release.
Please update to version 1.7.5 and try again.

**Comment by GIOkafor** [comment]
> @goalguy10
> 
> There was an issue with one of the dependency packages in 1.7.4. We've fixed it in our last release.
> Please update to version 1.7.5 and try again.

I'm on the latest version 1.8.2 and still getting this issue
