### ISSUE TITLE
Failed to start API Mock endpoint max retries hit

### ISSUE THREAD

**Issue by keenode** [aws-amplify/amplify-cli#2062]
**Describe the bug**
When I run `amplify mock`, after a few seconds the following error is returned:
```
Failed to start API Mock endpoint Error: max retries hit for starting dynamodb emulator
```
and hangs indefinitely. 

**To Reproduce**
1. Upgrade to latest amplify cli - 1.12.0
2. Have an existing initialized Amplify project with node modules installed (node 12 in my case). 
3. Run `amplify mock` at the root directory. 

**Expected behavior**
The command completes successfully and instructs the user on how to access the mock UI. 

**Desktop (please complete the following information):**
 - OS: macOS Mojave

**Additional context**
`npm start` to run the side locally, and all other amplify commands seem to be working properly.

**Comment by rakannimer** [comment]
Hey @keenode 

I think this is related to this issue : https://github.com/aws-amplify/amplify-cli/issues/2037

Can you try installing lsof ? 

Should be fixed with : https://github.com/aws-amplify/amplify-cli/pull/2061

**Comment by keenode** [comment]
@rakannimer Unfortunately, I've seen those other issues and have lsof installed already. :(
Still getting the error. Any ideas? 

Thanks for the help so far!

**Comment by yuth** [comment]
@keenode do you have Java installed on your machine? Mock uses DynamoDBLocal internally which is a java package and not having Java would cause this to fail

**Comment by keenode** [comment]
Hi @yuth 
Yes, I have had a version of java installed on my machine. I ran the command and it is located here:
/usr/bin/java

This is the version of Java I'm on:
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

**Comment by BryceAMcDaniel** [comment]
Hello all!

I am also receiving this message.  Similar java version to above.

Any further suggestions are appreciated.

Thanks!

**Comment by BryceAMcDaniel** [comment]
Fixed!

`brew cask install java`

worked for me.

**Comment by keenode** [comment]
@BryceAMcDaniel The brew install for java worked for me as well!

Thank you so much! :)

**Comment by niyazpk** [comment]
This is not a user error. The error message should be fixed so that others will not run into the same issue.

**Comment by janaka** [comment]
this is still an issue in 4.26.0. See more info in #4670

**Comment by jupitercow** [comment]
As of December 1, 2020:
`Error: Calling brew cask install is disabled! Use brew install [--cask] instead.`

> From the maintainer:
> ...
> brew cask commands were deprecated on 2020-12-01 with the release of Homebrew 2.6.0.

Use:
`brew install --cask oracle-jdk`

amplify --version: 4.40.1

**Comment by chinna2580** [comment]
unable to start the serverless.
still gets the following error:
Serverless: ERROR: Error: max retries hit for starting dynamodb emulator

i have the following java version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

lsof already installed
