### ISSUE TITLE
--no-gql-override not working on push

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#2334]
**Describe the bug**
I upgraded to the latest amplify (3.7.0) just now and I am now unable to push without compile.

**To Reproduce**
Issue the command "amplify push --no-gql-override" and it will still proceed to compile.

**Expected behavior**
I expect that the push would occur without compiling again.

**Screenshots**

$ amplify push --no-gql-override --yes

Current Environment: testapp

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Api      | testapp         | Update    | awscloudformation |
| Auth     | cognitoXXX | No Change | awscloudformation |

GraphQL schema compiled successfully.

**Additional context**
This is especially critical for me because the ConnectionStack.json file that amplify api gql-compile generates is 600KB - I need to minify that file so that is is less than the 460KB CloudFormation limit. So if I can't stop push recompiling this I have no way to minify and no way to deploy.

**Comment by attilah** [comment]
Fixed in https://github.com/aws-amplify/amplify-cli/pull/2336

**Comment by sacrampton** [comment]
I just updated the amplify cli and the issue still exists. When will it be released?

**Comment by kaustavghosh06** [comment]
We're shooting for end of day(PST) release - 9/18.

**Comment by kaustavghosh06** [comment]
We released the latest version of the CLI - 3.8.0 with this fix.
