### ISSUE TITLE
Fails to start api mock w/unhelpful error message

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-cli#2620]
**Describe the bug**
When trying to run a local mock of an API that is successfully deployed to the cloud using cli version 3.15.0, I get the following error:
```
Scanning for plugins...
Plugin scan successful

The following types do not have '@auth' enabled. Consider using @auth with @model
	 [redacted]
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth 


GraphQL schema compiled successfully.

Edit your schema at /[…]amplify/backend/api/[…]/schema.graphql or place .graphql files in a directory at /[…]amplify/backend/api/[…]/schema
Data source of type AMAZON_ELASTICSEARCH is not supported by local mocking. A NONE data source will be used.
Failed to start API Mock endpoint TypeError: Cannot read property 'name' of undefined

```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1
 - CLI Tools v3.15.0
 - Node v10.16.3

**Additional context**
My schema is fairly complex, comprising 30-some different data sources, custom resolvers and so on. I can push to AWS no problem, so not an enormous  deal, but would be nice to have local mocking capability for testing our custom resolvers.

**Comment by kaustavghosh06** [comment]
@nagey It would hard to reproduce and root cause this without taking a look at your project. If you're comfortable, you can send it to us at `amplify-cli@amazon.com` and we can take a look at it.

**Comment by attilah** [comment]
@yuth this is similar what I discovered back in the day and you fixed it IIRC, but perhaps the use case of replacing a DataSource type with NONE was not covered?

**Comment by nagey** [comment]
@kaustavghosh06 — just sent an email with a copy of the `amplify` folder to that address. Thanks in advance!

**Comment by chadkouse** [comment]
@nagey fwiw i got the error `Failed to start API Mock endpoint TypeError: Cannot read property 'name' of undefined` when running `amplify mock` as well.  Turned out my (manually build) stack needed to have things defined in a specific order within the json files -- specifically my data sources needed to come before any resolvers or functions that might reference them.

**Comment by kaustavghosh06** [comment]
We merged #3285 which addresses the unhelpful error message issue. Now the CLI will print out a better error message - for you to better root-cause the issue.

**Comment by nagey** [comment]
@kaustavghosh06 It's definitely different now, but I'm still seeing an issue getting this started — it's a problem with one of the auto-generated stacks, redacted output is below.

```
❯ amplify mock
Scanning for plugins...
Plugin scan successful
Mock Storage endpoint is running at http://localhost:20005

GraphQL schema compiled successfully.

Edit your schema at …/amplify/backend/api/capbase/schema.graphql or place .graphql files in a directory at …/amplify/backend/api/capbase/schema
Mock does not handle CloudFormation resource of type AWS::Elasticsearch::Domain. Skipping processing resource ElasticSearchDomain.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy01.
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource UnauthRolePolicy01.
Failed to start API Mock endpoint Error: Ref is missing in resource VestingScheduleTable
```

Any guidance here?

**Comment by yuth** [comment]
Mock does not support API that has `@searchable` directives. From the error it looks like it is failing to process the resources specific to `@searchable` directive.

**Comment by nagey** [comment]
@yuth it looks like it's just skipping the elasticsearch piece of it, but does that disqualify using the entire stack from a mock perspective? is that slated for improvement?

even if that is the case though, I would suggest that the error `Ref is missing in resource VestingScheduleTable` is not super helpful — that table is searchable, but is that the error, or what?

**Comment by yuth** [comment]
we could definately improve this and add support for all query/mutations except for the `search*` queries. Let me mark this as enhancement for mock

**Comment by nagey** [comment]
@yuth — I would suggest, in this case, that the `search*` queries actually get left intact in the schemas, but the resolvers give a simple standard empty reply no matter what the query (or a reply that makes it clear that it isn't implemented in mock, or something. That way you can use the mock code without front-end implications, or really hopefully any implications on the generated code that goes into a client

**Comment by quorth0n** [comment]
Any updates on this feature?

**Comment by royalaid** [comment]
I too am suffering from "Failed to start API Mock endpoint Error: Ref is missing in resource *" and wondering what the status on this issue is or if there is something I can do to debug the issue locally

**Comment by kevcam4891** [comment]
Disappointing that mock can't even get going when you've got ElasticSearch data sources. I've tried removing the `@searchable` part, but I end up with a string of other errors I can't make out yet related to resolvers.

**Comment by nagey** [comment]
So, It's been over a year since I wrote this initial issue, and I figured, hey, what the heck, it's been a year, maybe the mock works better these days!

So, I try running the mock on my project.

I get an error.

I search the error.

I get the same issue I opened a year ago.

AWeSome.

Maybe we can re:invent the mock so that it'll work in a wider range of situations so that we don't have to spend 40 minutes pushing code for a one line lambda change :-/

**Comment by overflowz** [comment]
Having the same issue here and been waiting for it for a long time now. Also, is the `enhancement` label correct here? Shouldn't it be a bug since it causes mock to fail?

**Comment by ezkemboi** [comment]
```Maybe we can re: invent the mock so that it'll work in a wider range of situations so that we don't have to spend 40 minutes pushing code for a one-line lambda change :-/```

@nagey any plans or resolutions?
Pushing code each time really affects development time, impacting both the developer & business. 
I would love to see mocking becoming better & efficient.
