### ISSUE TITLE
Multi Auth - public acces failed

### ISSUE THREAD

**Issue by mlafo** [aws-amplify/amplify-cli#3724]
**Describe the bug**
Unauthenticated GraphQl request failed with an "No current user" error return.
Is there something i am doing wrong or is it a bug ? 

**To Reproduce**

_GraphQL transform Schema_

```graphql
type Mutation 
{
shareFiles(fileIds: [String], emailContacts: [EmailContactInput], msg: String): SharedFilesOutput @function(name: "shareFile-${env}:final")
	rewewShareFiles(token: String): RenewSharedFilesOutput @function(name: "shareFile-${env}:final")
	@auth(rules: [{allow: public, provider: iam}]) 
}

```
_Authorised provider in AppSync are  IAM and Amzon Cognito User Pool_

_Front End is builded with reactJs._
Request to shareFiles works with an user authenticated with Cognito but request to rewewShareFiles does works with an user unauthenticated and return an "No current user"

Like seen in several docs, the React component for unauthenticated request is builded like this : 

`Amplify.configure(aws_exports);`

```js
class Renew extends Component {
  constructor() {
    super();
    this.state = {
      token: null,
      result: { empty: true }
    };
    this.renewShareFiles= this.renewShareFiles.bind(this);
  }
  async componentDidMount() {
    await Auth.currentCredentials()
      .then(d => console.log("cognito Credentials data: ", d))
      .catch(e => console.log("cognito Credentials error: ", e));

    const query = new URLSearchParams(window.location.search);
    const token = query.get("t");
    if (token !== "null") {
      this.setState({ token: token });
      this.shareFile(token);
    }
  }
async renewShareFiles(token) {
    const mutationName = "rewewShareFiles";
    try {
      let res = await API.graphql(
        graphqlOperation(mutations[mutationName], {
          token: token,
        })
      );
      return res;
    } catch (err) {
      console.log(
        "AppSyncRequest rewewShareFiles : error: ",
        err
      );
      return false;
    }
  }
/...

```
Auth.currentCredentials() returns unauthenticated credentials  with  secretAccesKey and sessionToken but renewShareFiles() fails. 

**Amplify version**
3.17.0

**Comment by sammartinez** [comment]
@mlafo Thanks for getting back to me, this seems to be a possible issue with Amplify CLI. I have transferred the issue to their repo.

**Comment by ammarkarachi** [comment]
@mlafo Can you try the latest release we have fixed it in 4.17.2 in PR #3590

**Comment by mlafo** [comment]
Il works. Thanks a lot.

**Comment by ohsik** [comment]
I see below adds `arn:aws:appsync:us-east-1:991498611366:apis/3a3c6gaotrcsdosxxq25d2lnpa/types/Mutation/fields/customMutation` to authRole and unauthRole under IAM.
```
type Mutation {
    customMutation(username: String!, expoNotificationToken: String!): AWSJSON @function(name: "customMutation-${env}") @auth(rules: [{ allow: public, provider: iam }])
    customMutation2(username: String!, expoNotificationToken: String!): AWSJSON @function(name: "customMutation2-${env}")
```
However, I still get a 401 error when I call it with 
```
      const result = await API.graphql({
        query: mutations.customMutation,
        variables: {
          username: "test",
          email: "test2"
        },
        authMode: 'AWS_IAM'
      });
```

Does it work with mutation as well? or it's not supported?
