### ISSUE TITLE
The input value type 'ModelAttributeTypes' is not present when resolving type

### ISSUE THREAD

**Issue by isheejong** [aws-amplify/amplify-cli#4081]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I have reinstalled the amplify CLI (4.18.1) and modified a schema.graphql . but, it was failed when amplify push.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
```
isheejong@gmail.com:~/environment $ amplify -v
4.18.1
```
**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**1. modified the schema.grapql to below content.**
```graphql
type Cart 
@model(queries: null, mutations: null, subscriptions: null)
@aws_api_key
@aws_cognito_user_pools
@key( fields : ["sessionId"], name: "sessionId")
{
  id : ID!
  memberId:String
  sessionId: ID
  cartType: CART_TYPE!
  cartName: String!
  orderSummary: AWSJSON
  orderSummaryInfo: AWSJSON 
  createTime: AWSDateTime
  updateTime: AWSDateTime
  cartItems: [CartItem] @connection(name:"CartCartItem")
}

type CartItem 
@model(queries: null, mutations: null, subscriptions: null)
@aws_api_key
@aws_cognito_user_pools
{
  id: ID!
  productNo: String!
  itemNo: String!
  productType: PRODUCT_TYPE! 
  packageNo: String!
  sellerId: String!
  productName: String! 
  itemName: String!
  itemPrice: Float! 
  itemQty: Float! 
  cartItemInfo: AWSJSON 
  cart: Cart @connection(name:"CartCartItem")
}

enum CART_TYPE {
  MEMBER
  SESSION
}

enum PRODUCT_TYPE {
  UNIT
  PACKAGE
}

type Query {
  getMyCart:Cart
  getCartBySessionId(sessionId:String!):Cart
}

input CreateCartInput{
  cartType: CART_TYPE!
  cartName: String!
  orderSummary: AWSJSON
  orderSummaryInfo: AWSJSON
}

input UpdateMyCartInput{
  memberId: String!
  orderSummary: AWSJSON
  orderSummaryInfo: AWSJSON
}

input UpdateCartInputBySessionId{
  sessionId: String!
  orderSummary: AWSJSON
  orderSummaryInfo: AWSJSON
}

type Mutation{
 
  createCart(input: CreateCartInput!):Cart
  @aws_cognito_user_pools
  @aws_api_key
  
  updateMyCart(input: UpdateMyCartInput!):Cart
  @aws_cognito_user_pools
  
  updateCartBySessionId(input: UpdateCartInputBySessionId!):Cart
  @aws_api_key

}
```
**2. amplify push** 

**Expected behavior**

** you can see following errors.**
```
Resource Name: zaic7uucg5fcjnuysj35hs4ba4GraphQLSchema (AWS::AppSync::GraphQLSchema)
Event Type: update
Reason: Schema Creation Status is FAILED with details: Found 6 problem(s) with the schema:
The input value type 'ModelAttributeTypes' is not present when resolving type 'ModelStringInput' [@151:1].
The input value type 'ModelAttributeTypes' is not present when resolving type 'ModelIDInput' [@167:1].
The input value type 'ModelAttributeTypes' is not present when resolving type 'ModelIntInput' [@183:1].
The input value type 'ModelAttributeTypes' is not present when resolving type 'ModelFloatInput' [@195:1].
The input value type 'ModelAttributeTypes' is not present when resolving type 'ModelBooleanInput' [@207:1].
The input value type 'ModelPRODUCT_TYPEInput' is not present when resolving type 'ModelCartItemFilterInput' [@224:1].
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubunt, cloud9
 - Node Version. You can use `node -v` to check the node version on your system
```
isheejong@gmail.com:~/environment $ node -v
v10.19.0
```

**Additional context**

**Comment by edwardfoyle** [comment]
@isheejong I was able to repro this. While we work on a fix, you can get around the issue by adding the following to your graphql schema:
```graphql
enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}
```

**Comment by isheejong** [comment]
> @isheejong I was able to repro this. While we work on a fix, you can get around the issue by adding the following to your graphql schema:
> 
> ```graphql
> enum ModelAttributeTypes {
>   binary
>   binarySet
>   bool
>   list
>   map
>   number
>   numberSet
>   string
>   stringSet
>   _null
> }
> ```

Thank you for sharing the work around :)

**Comment by edwardfoyle** [comment]
@isheejong This is fixed in the latest version of the CLI (4.19.0)

**Comment by isheejong** [comment]
Thank you very much : ) I will test on it.

**Comment by iShavgula-TacTill** [comment]
I'm still having the issue with Amplify 4.19.0.

> The input value type 'ModelSTOCK_MOVEMENT_STATEInput' is not present when resolving type 'ModelStockMovementHistoryFilterInput'

`StockMovementHistory` is a `@model` type without queries or mutations and is referenced via a `@connection` from another type.
`STOCK_MOVEMENT_STATE` is an enumeration present in `StockMovementHistory`.

**Comment by yonatanganot** [comment]
We also have this issue in Amplify 4.19.0.

**Comment by iShavgula-TacTill** [comment]
I tried to recreate the whole projet and everything worked fine, but the bug still persists on existing project.
Hope this helps.

**Comment by edwardfoyle** [comment]
@iShavgula-TacTill @yonatanganot are you seeing an issue with the AttributeTypeEnum not being included in your schema or some other custom enum? If it's a custom enum, please open another issue so we can track that separately

**Comment by iShavgula-TacTill** [comment]
I’m having the issue with a custom enum, which is also one of the errors described in the original post of this issue. 

Here is copy of it:
The input value type 'ModelPRODUCT_TYPEInput' is not present when resolving type 'ModelCartItemFilterInput' [@224:1].

Does that mean that the 4.19.0 is not meant to fix the issue with custom enums?

**Comment by edwardfoyle** [comment]
@iShavgula-TacTill Sorry, I missed that custom enums were also part of the error in the original post. No, the current version does not fix that issue. The above PR addresses that problem.

**Comment by edwardfoyle** [comment]
The fix for this has been released. Please install the latest version of the CLI to get the updates.
