### ISSUE TITLE
GraphQL Transform AppSync service error: not supported through the realtime channel

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#4118]
**Describe the bug**
I am trying out this tutorial here: https://dev.to/playra/aws-datastore-283f

I'm trying to get subscriptions working through AWS AppSync Console on the queries tab, but the service is returning a bunch of errors.

- schema uses model and auth directive,
- backend provisioned for DataStore
- no libraries used, tests done through AWS AppSync Console

**Amplify CLI Version**
`4.18.0`

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
1. `amplify init`, `amplify add auth`, choose email
2. `amplify add api`, Use this schema,
```
type Job
  @model
  @auth(
    rules: [
      {allow: owner, ownerField: "owner", operations: [create, update, delete]},
    ])
{
  id: ID!
  position: String!
  rate: String!
  description: String!
  owner: String
}
```
3. `amplify update api`, choose enable for DataStore
4. `amplify push`
5. `amplify console auth`, user pools, create a user with verified email, note the sub of the user, grab the app client id from the other tab as well,
5. amplify console api, Queries tab, login using the app client id, email, and password, will prompt to update password, then make sure you are logged in.
6. Create a new Job
```
mutation createJob($input: CreateJobInput!) {
  createJob(input: $input) {
    id
    position
    rate
   description
    owner
    _version
    _deleted
    _lastChangedAt
  }
}
{
  "input": {
    "id": "111",
    "position": "1",
    "rate": "100",
    "description": "desc",
    "owner": "eb8f6fc5-78b7-41a1-b1fa-9bc6dd61bdb7" // replace this with your sub 
  }
}
```
7. Job is created successfully. Open another console to create a subscription on the data
```
subscription onCreateJob($owner: String!){
  onCreateJob(owner: $owner) {
    id
    position
    rate
    description
    owner
    _version
    _deleted
    _lastChangedAt
  }
}
{
  "owner": "eb8f6fc5-78b7-41a1-b1fa-9bc6dd61bdb7"
}
```
8. Fails with 
```
Error: {
    "errors": [
        {
            "message": "Connection failed: {\"errors\":[{\"errorType\":\"UnsupportedOperation\",\"message\":\" not supported through the realtime channel\"}]}"
        }
    ]
}
    at Object.error (https://d2i3s4ccv6vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:135:834636)
    at d (https://d2i3s4ccv6vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1290919)
    at m (https://d2i3s4ccv6vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1291263)
    at e.value (https://d2i3s4ccv6vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:174:1292345)
    at n._handleIncomingSubscriptionMessage (https://d2i3s4ccv6vp01.cloudfront.net/c838cd42dec424b3e3864f2d31611d91308b8975/main.js:135:664618)
```

**Expected behavior**
Subscriptions work as expected. 

**Additional context**
So interestingly this was working earlier: I was able to create a subscription connection, go back to other tab and create a Job mutation. my subscription got a bad response because because i missed putting `description` in the selection set of the createMutation and subscription had selection set with description was expecting non-null description to come back.. So i wonder if that caused the AppSync service to be in a weird state and now I can't get the subscriptions to connect anymore.

When i miss adding the required selection set in the createJob mutation, the subsription received this error:
```
{
  "data": {
    "onCreateJob": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable type: 'String' within parent 'Job' (/onCreateJob/description)",
      "path": [
        "onCreateJob",
        "description"
      ]
    }
  ]
}
```

**Comment by lawmicha** [comment]
thanks @yuth  

When using the AWS AppSync console to create subscriptions, make sure your document only has that single operation. I had two since i wanted to test the onCreateJob and onUpdateJob

**Comment by lawmicha** [comment]
Reopening the issue, got some feedback from https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/372#issuecomment-660361938

- Why doesn't it work when there is more than a single operation?
- Depending on answer above, we can improve documentation around debugging, and identify any long term plans

**Comment by palpatim** [comment]
@flywheelms Did you close this because it was resolved via documentation updates or a bug fix?

**Comment by blau2** [comment]
This is still an issue. When trying to establish a subscription through the AppSync console, it fails when there is more than a single operation present. It works fine as long as the subscription is the only operation.

**Comment by lawmicha** [comment]
Reason why this fails: mutations and queries are sent as an HTTP request while subscriptions are sent to the websocket endpoint. 

Workaround is to open 2 tabs, 1 for queries/mutations and another for subscriptions

What is a better developer experience? I don't think we should over index on catching a development time bug with a runtime solution. The service is already returning an error message, perhaps just not enough information about why it failed.

Is there an error message that can be created in this context? such as
```
Connection failed: {\"errors\":[{\"errorType\":\"UnsupportedOperation\",\"message\":\"query and mutations are not supported through the realtime channel, make sure you are only sending subscription operations to this endpoint.\"}
```

My take on this is to update the right side panel after clicking on `info`
![image](https://user-images.githubusercontent.com/1365977/109174425-b2b54f00-7739-11eb-8bc2-8bb3f3bb20d3.png)

and/or add an entry to [AppSync's Troubleshooting and Common Mistakes page](https://docs.aws.amazon.com/appsync/latest/devguide/troubleshooting-and-common-mistakes.html)

The info we can add is


## Connection Failed: Unsupported Operation

If you execute multiple GraphQL operations at the same time, such as having both a query/mutation and a subscription, you will get the following error:
```
"message": "Connection failed: {\"errors\":[{\"errorType\":\"UnsupportedOperation\",\"message\":\" not supported through the realtime channel\"}]}"
```
The AppSync endpoint cannot handle both types of operations at the same time since query and mutations are sent to the HTTP endpoint and subscriptions are sent to the websocket endpoint. Make sure to open a second tab for testing subscription operations by itself.
