### ISSUE TITLE
Amplify cli Mock not filter subscription by fields like on online AppSync version

### ISSUE THREAD

**Issue by TrungRueta** [aws-amplify/amplify-cli#4725]
**Describe the bug**
I follow instruction section "Filter subscription" in this [Filter subscription](https://docs.amplify.aws/cli/graphql-transformer/examples#filter-subscriptions-by-model-fields-andor-relations). After done 3 steps (push all really). i run cli
`amplify mock` and try custom subscription with filter by id but look like in mock api it always response to subscription without filter by id.

I also try same in appsync cloud, api on appsync api working well, so issue from mock version

**Amplify CLI Version**
`4.22.0`

**To Reproduce**
Do follow the instruction in describe the bug section. i also attack my own simple graphql schema below

```graphql
type Subscription {
  onTaskUpdate(key: String!): Task @aws_subscribe(mutations: ["setTask"])
}

type Task
  @model(mutations: { create: "setTask" }, subscriptions: null)
  @key(fields: ["key"])
  @auth(rules: [{ provider: iam, allow: private }]) {
  key: String!
  value: AWSJSON!
}
```

**Expected behavior**
Mock version should filter subscription by any fields same appsync online version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. `10.20.1`

**Additional context**

**Comment by half2me** [comment]
+1, This would be important for me as well.

**Comment by SwaySway** [comment]
@TrungRueta @half2me 
Closing this issue as this fix was merged and included in the latest release.

PR which addressed this fix: https://github.com/aws-amplify/amplify-cli/pull/3912

**Comment by mgarabedian** [comment]
I have the same issue with the latest amplify cli version (4.41.2). Create or Update subscriptions are calling on every mock request, regardless of variables sent. It's hard to know if I am doing something wrong, or what the case is.

**Comment by iyz91** [comment]
@SwaySway As far as I can tell, this problem still exists (also using 4.41.2). Please address this for mocks, it's very convenient.

**Comment by tamerfahmy** [comment]
@SwaySway I have the same issue. I am using 4.45.0

**Comment by sbouchard1** [comment]
@SwaySway @yuth Still still have the issue with version 4.50.2.
