### ISSUE TITLE
`amplify push` always errors out if gql schema does not have a subscription

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#475]
**Describe the bug**
I am creating a GraphQL API using GraphQL Transformer. My API does not have any subscriptions and I am using the feature of removing it as described here: https://aws-amplify.github.io/docs/cli/graphql#usage 

```graphql
type Post @model(queries: { get: "post" }, mutations: null, subscriptions: null) {
    id: ID!
    title: String!
    tags: [String!]!
}
```

When I do `amplify push` with the schema, the resource creation succeeds but the cli spews out an error message and leaves my resource in a `Create` state always.

```bash
✔ Generated GraphQL operations successfully and saved at graphql
2018-11-17T05:05:09.589Z - error: uncaughtException: Schema is not configured for subscriptions date=Fri Nov 16 2018 21:05:09 GMT-0800 (PST), pid=87711, uid=420918404, gid=1896053708, cwd=/Users/******/*******, execPath=/usr/local/Cellar/node/10.2.1/bin/node, version=v10.2.1, argv=[/usr/local/Cellar/node/10.2.1/bin/node, /usr/local/bin/amplify, push], rss=121409536, heapTotal=90583040, heapUsed=65455288, external=515955, loadavg=[1.98681640625, 2.17529296875, 2.41552734375], uptime=1155151, trace=[column=15, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/utilities/graphql.ts, function=Object.getOperationRootType, line=179, method=getOperationRootType, native=false, column=22, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/compiler/index.ts, function=Compiler.compileOperation, line=238, method=compileOperation, native=false, column=36, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/compiler/index.ts, function=Object.compileToIR, line=148, method=compileToIR, native=false, column=21, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/generate.ts, function=generate, line=37, method=null, native=false, column=7, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js, function=projects.forEach, line=39, method=forEach, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=14, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js, function=generateTypes, line=22, method=null, native=false, column=3, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/callbacks/postPushCallback.js, function=postPushCallback, line=34, method=null, native=false, column=7, file=internal/process/next_tick.js, function=process._tickCallback, line=68, method=_tickCallback, native=false], stack=[Schema is not configured for subscriptions, , graphql/subscriptions.graphql (2:1), 1: # this is an auto generated file. This will be overwritten, 2: subscription OnCreateScore {,    ^, 3:   onCreateScore {, ,     at Object.getOperationRootType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/utilities/graphql.ts:179:15),     at Compiler.compileOperation (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/compiler/index.ts:238:22),     at Object.compileToIR (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/compiler/index.ts:148:36),     at generate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/generate.ts:37:21),     at projects.forEach (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js:39:7),     at Array.forEach (<anonymous>),     at generateTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js:22:14),     at postPushCallback (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/callbacks/postPushCallback.js:34:3),     at process._tickCallback (internal/process/next_tick.js:68:7)]
```

**Expected behavior**
Success message

**Comment by mikeparisstuff** [comment]
I believe this is an error with codegen. @yuth are you aware of this?

**Comment by yuth** [comment]
@rohandubal I could not reporduce this error either in an Swift project or in a JS project. What frontend are you using?

**Comment by kaustavghosh06** [comment]
@rohandubal  This issue is fixed with the latest version of the CLI.

**Comment by artyhedgehog** [comment]
@kaustavghosh06 I still get the error on 1.9.0:
```
$ amplify push
...
- Generating2019-08-01T12:47:18.848Z - error: uncaughtException: Schema is not configured for subscriptions date=Thu Aug 01 2019 15:47:18 GMT+0300 (Moscow Standard Time), pid=20024, uid=null, gid=null, cwd=C:\Users\PC\ws\andersen\ryanair\customer-enquiries, execPath=C:\Program Files\nodejs\node.exe, version=v10.16.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\@aws-amplify\cli\bin\amplify, push], rss=234266624, heapTotal=183066624, heapUsed=135381632, external=25261889, loadavg=[0, 0, 0], uptime=107153, trace=[column=15, file=C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\utilities\graphql.ts, function=Object.getOperationRootType, line=179, method=getOperationRootType, native=false, column=22, file=C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\compiler\index.ts, function=Compiler.compileOperation, line=238, method=compileOperation, native=false, column=36, file=C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\compiler\index.ts, function=Object.compileToIR, line=148, method=compileToIR, native=false, column=19, file=C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\compiler\legacyIR.ts, function=Object.compileToLegacyIR, line=96, method=compileToLegacyIR, native=false, column=21, file=C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\generate.ts, function=generate, line=90, method=null, native=false, column=7, file=C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-codegen\src\commands\types.js, function=projects.forEach, line=50, method=forEach, native=false, column=7, file=internal/process/next_tick.js, function=process._tickCallback, line=68, method=_tickCallback, native=false], stack=[GraphQLError: Schema is not configured for subscriptions,     at Object.getOperationRootType (C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\utilities\graphql.ts:179:15),     at Compiler.compileOperation (C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\compiler\index.ts:238:22),     at Object.compileToIR (C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\compiler\index.ts:148:36),
     at Object.compileToLegacyIR (C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\compiler\legacyIR.ts:96:19),     at generate (C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-graphql-types-generator\src\generate.ts:90:21),     at projects.forEach (C:\Users\PC\ws\andersen\ryanair\customer-enquiries\node_modules\amplify-codegen\src\commands\types.js:50:7),     at process._tickCallback (internal/process/next_tick.js:68:7)]
```
My schema is as follow:
```
type Enquiry @model(subscriptions: null) {
  ...
}

type EnquirySubmission @model(queries: null, subscriptions: null) {
  ...
}
```

Codegen operation is update. Previously it was just:
```
type Enquiry @model {
```
 - maybe that's the cause of an issue?
