### ISSUE TITLE
Import/require path for custom lambda layer function is wrong

### ISSUE THREAD

**Issue by iaarnio** [aws-amplify/amplify-cli#4822]
**Describe the bug**

Amplify CLI creates directories `opt/` and `lib/`.  The first one is for functions that you want to share with other lambdas.  However, if you create custom function e.g. `opt/param.js` you need to require/import it in lambdas using path `/opt/opt/param`. This does not feel 'right' and is confusing for users.

Amplify CLI: 4.23.0

**To Reproduce**

1. Initialize Amplify project using amplify init
2. Create lambda layer using amplify add function
3. Add custom (exported) function to the lambda layer `opt/` folder 
4. Create lambda function using amplify add function
5. Import lambda layer custom into this lambda. Note that you need to use `/opt/opt` as path to successfully require the function.

**Expected behavior**

More logical path would be `/opt/{moduleFileName}`. E.g.  `require('/opt/param');`.

**Code Snippet**

Lambda layer code in file `./amplify/backend/function/common/opt/param.js`:
```
const getValue = async (name) => {
  // business logic
}
module.exports = getValue;
```

Lambda code to require the above function:
```
const getValue = require('/opt/opt/param'); // developer would expect require('/opt/param') to work
```

**Comment by jhockett** [comment]
Hi @iaarnio, thanks for the bug report as well as the workaround! For the time being, we've updated the docs about the path while we work on a fix.

https://github.com/aws-amplify/docs/pull/2104

**Comment by jhockett** [comment]
A fix has been released in 4.25.0. For new Lambda layer versions, files and folders placed in the local `/opt/` directory can be imported from `/opt/` in the dependent Lambda functions.

**Comment by Usama-Tahir** [comment]
I am still facing this issue. I have tried both `/opt/<moduleName>` and `/opt/opt/<moduleName>`. I am getting this error.

```
"errorType": "Runtime.ImportModuleError", "errorMessage": "Error: Cannot find module '/opt/test'\nRequire stack:\n- /var/task/app.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
```

I am can successfully use node modules in my lambda function from the lambda layer though.

My amplify.yml file partially looks like this for the backend part.
```
backend:
  phases:
    build:
      commands:
        - '# Execute module build for lambda layers'
        - cd ./amplify/backend/function/viewerlayer/lib/nodejs
        - yarn install
        - echo "# Back to root folder"
        - cd ../../../../../..
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```


I am importing it in App.js file like this.

```
const getValue = require('/opt/test');

```


test.js file is like this.
```
const getValue = async () => {
  console.log('Gets Called!');
};
module.exports = getValue;

```


test.js path is:
`amplify/backend/function/viewerlayer/opt/test.js`
