### ISSUE TITLE
Headless push with Aurora doesn't work

### ISSUE THREAD

**Issue by Dextavision** [aws-amplify/amplify-cli#5536]
### Description
Hello!
For around 3 days i faced issues with deploying my angular app via Amplify Console. I tried it with different Amplify CLI versions.
Right now i updated my amplify and amplify CLI package inside my project to the newest one:
**aws-amplify: 3.0.22**
**aws-amplify/cli: 4.26.0**

In my project im using Amplify **Auth** and an **GraphQL API** with an **Aurora RDS.** I deployed everything in eu-central-1 **BUT the Aurora RDS is in eu-west-1 because at the time i build the project Aurora RDS via amplify was not supported in eu-central-1.**

If i now run the deployment i got this "info" at the build stage and it failed as soons as the timeout time is reached (20 minutes):
![image](https://user-images.githubusercontent.com/50227132/89159073-48577a00-d56f-11ea-82a6-8f4b2a60f645.png)

I thought maybe its because of the team-provider file. I dont have it in my git repo because of the client_secrets of Facebook and Google that i use for federated sign in.

Im thankful for any help so i can finaly deploy my app.

Best Regards

**Comment by Dextavision** [comment]
@swaminator thanks for the reply.
I was able to publish the app by leaving the backend off from amplify. So i just deployed the frontend via the amplify console and that worked fine.
Maybe that helps others that face this issue.

Have a great day 👍

**Comment by ammarkarachi** [comment]
@Dextavision The region choice is showing up because it cannot find the region in the team-provider-info. I will keep this up for review by the team

**Comment by jcvalerio** [comment]
@ammarkarachi  this issue still present on latest version like `4.32.1`

We use the *PR Preview* feature, so we have to create the environment at runtime, so add those values on the `amplify/team-provider-info.json` is not an option

we have a custom `amplifyPush` to do the headless workflow but this didn't work because, the amplify console have no idea of how handle the `RDS` settings


At the Amplify Console the build got stuck, but nothing was shown 

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/2169894/108138211-15944f80-7083-11eb-8f88-373deb808824.png">


Running the script locally with the same env variables

<img width="950" alt="image" src="https://user-images.githubusercontent.com/2169894/108138445-9c492c80-7083-11eb-9bc7-4546d7e81dd0.png">

We can see the console got stuck waiting for user confirmations
