### ISSUE TITLE
Can not deploy app!! Environments problems

### ISSUE THREAD

**Issue by carlosortizpacheco** [aws-amplify/amplify-cli#5862]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Hi, I'm trying to deploy an app with React. I had never experience a problem like this until I udpated amplify-cli . The deploy Its stucked because do not find the environment (dev or prod). I created another environment just to check if I can deploy it with no success. In team-provider-info.json are both environments.

**Amplify CLI Version**
amplify-cli (4.32.1)

**Expected behavior**
Deploy app

**Screenshots**
020-11-14T02:20:35.297Z [WARNING]: - Initializing your environment: prod
2020-11-14T02:20:35.317Z [WARNING]: (node:1969) ExperimentalWarning: The fs.promises API is experimental
2020-11-14T02:20:35.394Z [INFO]: Environment 'prod' not found.
2020-11-14T02:20:35.394Z [INFO]: Try running "amplify env add" to add a new environment.
                                 If this backend already exists, try restoring it's definition in your team-provider-info.json file.

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Node 12.16.3

**Comment by SourceCode** [comment]
You can backup your amplify directory and re-init or re-pull the environment.  You can go to the environment via `amplify console` and then click backend and it will have the correct pull command for the env & app.

**Comment by carlosortizpacheco** [comment]
Hi, I tried to erase the amplify folder before and re run amplify init command, without success... Today I delete again the amplify folder and finally can deploy it. I had some problems because git add aws-exports.js file to gitignore...I havent had this problem before...Maybe git add team-provider.info.json to gitignore and cannot find the environment...

Thanks....

**Comment by Jhenri-silva** [comment]
go to the cloud formation in aws console and update the stack, I think there are serveral steps into that changes, but I found that way more quickly to update team-provider-info

**Comment by drclohite** [comment]
similar issue here too. Been a problem since last CLI update about a week ago.

**Comment by chrisboyce** [comment]
Ok, good to know I'm not the only one. The error would be a lot more helpful if it told me how to go about restoring the definition. The CLI has gotten to the point where I try not to change anything for fear for breaking all my environments in some incomprehensible way.

**Comment by carlosortizpacheco** [comment]
Hi, I though my problem had been resolve, but today I tried to make a new deployment, unfortunately the deployment stucks in "provision" state...someone know how to solve this???..I tried to deploy the last version, the one that I can deployed without problems, but the same problem appears...

**Comment by jhockett** [comment]
Hi @carlosortizpacheco. A number of AWS services, including Amplify Console, are experiencing issues over the past several hours and is likely the deployment failed.

Just to double check if it's unrelated, can you describe the steps you took?

**Comment by carlosortizpacheco** [comment]
> Hi @carlosortizpacheco. A number of AWS services, including Amplify Console, are experiencing issues over the past several hours and is likely why the deployment failed.
> 
> Just to double check if it's unrelated, can you describe the steps you took?

Hi, @jhockett, I have just deployed again my app without problems... surely was the outage. Thanks

**Comment by jhockett** [comment]
Sounds like your issue is resolved then @carlosortizpacheco. Closing this issue.

@drclohite looks like the issue you're experiencing is more likely related to #5931.

**Comment by MontoyaAndres** [comment]
Thanks @SourceCode this problem still persists in version 4.36.2
