### ISSUE TITLE
Feature Request - automated deployment for larger projects

### ISSUE THREAD

**Issue by kenbankspeng** [aws-amplify/amplify-cli#6387]
**Is your feature request related to a problem? Please describe.**
Since for larger projects, due to the number of policies that Amplify injects into authRole for the various required Lambda permissions, the push of the Amplify deployment will fail since AWS limitations on total role size will be greatly exceeded. 

As a fallback, I have created an optimized permissions authRole policy that is much smaller allowing us to stay under the AWS policy role limitations. 

Unfortunately deployment now involves manual participation that while the deployment push is running, I must delete the inline IAM policy statements fast enough as they are being generated and pushed by Amplify so as to remain under the AWS limit.

Failure to due so will result in an error and Amplify will revert the entire deployment.

**Describe the solution you'd like**
An automated deployment for larger projects

**Describe alternatives you've considered**
Serverless

Thank you.

**Comment by attilah** [comment]
@kenbankspeng thanks for the suggestion we are aware of the issue and as it is addressed for GraphQL APIs we plan to support it for other resources to unblock customers with larger projects.

**Comment by MaximilianSchon** [comment]
@attilah It says that #2084 is closed because the issue has been adressed on the current CLI, but I still get this issue on the current (5.1.2) CLI.

**Comment by ykethan** [comment]
Hey @kenbankspeng, are you still experiencing this issue. Please refer to https://github.com/aws-amplify/amplify-cli/issues/2084 mitigating this.

**Comment by pull-task-dev** [comment]
The authRole permissions are constructed much more efficient than it used to be while still targeting fine grain configurability. I can manually optimize permissions for my application much better, but I can see why that is not easily achieved by Amplify-CLI while still supporting fine grain. This can be closed.
