### ISSUE TITLE
Amplify Auth signup flow, account creation -- Impossible to set up email-only verification

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#7666]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

5.1.0 - 5.4.0

### What operating system are you using?

Debian 10 Linux (Buster)

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

After setting up a Graphql API via the `amplify add api` command, and giving it both IAM and Cognito auth - then running `amplify auth update` command to set up a post confirmation lambda - those two commands end up in a locked up Cognito console (Cognito console -> User Pools -> General Settings -> MFA and verification section) which: 
1) shows the wrong defaults in it - it is supposed to have email verification because I asked for it in the above amplify cli setup commands, but it says "No verification" instead.
2) when you try to choose "Email" under the section "Which attributes do you want to verify?" it won't let you save this change with a red warning at the bottom that says "MFA cannot be turned off if an SMS role is configured"
    **BUT MFA was configured to OFF** already via the Amplify CLI command - so this error message that disables making any changes is not making any sense.
3) when you try another change another question: "How will a user be able to recover their account?" to "Email only" from how it shows up, which isn't email-only it is the "not recommended" option (that is the option that gets selected for us by default for that question, which also seems like the wrong default answer to set up for us here, it should be "email only", given that I asked for that in the amplify cli command `amplify add api`) 

See transcripts and screenshots below...

### Expected behavior

I expected the Cognito console (User Pools -> General Settings -> MFA and verification section) to: 
1) Show "Email only"  as the selected answer, under the question "How will a user be able to recover their account?", instead of showing the selected answer to be something else, namely " (Not Recommended) Phone if available, otherwise email, and do allow a user to reset their password via phone if they are also using it for MFA."
   **NOTE:** -------> we have never set up anything related to phones in this amplify run!
2) Show "Email" as the selected answer, under the question "Which attributes do you want to verify?" but instead it shows "No verification" - but that is not what we asked for in the cli setup when running `amplify add api` - we asked for email-only verification there... (see reproduction steps below)
3) (see 1 above) now that it does not show "Email only" at least let us update it to that, but the console does not let us update any answer to this question, because when we click "save" it says "MFA cannot be turned off if an SMS role is configured" -- **but we have never turned MFA on in the first place!!** we never touched MFA, nor have we touched any phone stuff or phone settings here - we have set up MFA as OFF in the `amplify auth update` part of the scaffolding
4) Similarly, We are not allowed to change (see 2 above) to "Email" - same non-sensical error "MFA cannot be turned off"

#### 1) Set up a graphql API via the Amplify CLI
```bash
dtal@thing5: amplify add api
? Please select from one of the below mentioned services: GraphQL
? Provide API name: tracktunes
? Choose the default authorization type for the API IAM
? Do you want to configure advanced settings for the GraphQL API Yes, I want to make some additional changes.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API Amazon Cognito User Pool
Cognito UserPool configuration
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to configure advanced settings? No, I am done.
Successfully added auth resource tracktunes8f2ab495 locally
```

#### 2) Do an `auth update` for adding a post-confirmation trigger lambda
```bash
dtal@thing5: amplify auth update
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for 
images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Confirmation
? What functionality do you want to use for Post Confirmation Create your own module
Successfully added resource tracktunes8f2ab495PostConfirmation locally.
```
#### 3) Check the Cognito console - this is what you'll see
But why?  This is wrong. It should select "Email only" for the first question and "Email" for the second and not give us warnings. These warnings don't make any sense - we haven't touched SMS in this app, we are not using it at all. The first warning says we have not selected email or phone number but that's not true, we have selected email....
![s1](https://user-images.githubusercontent.com/5935957/124516465-b32cb900-ddaf-11eb-8351-795d65d6b210.png)

#### 4) Try to change either of the two questions above and then save, you'll get something like this:
(in this case changing both questions at once but the red error shows up also when you try them one at a time)
![s2](https://user-images.githubusercontent.com/5935957/124516716-4bc33900-ddb0-11eb-93da-b1435c0c5589.png)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

See this other related  issue here: https://github.com/aws-amplify/amplify-js/issues/8539

**Comment by dorontal** [comment]
I noticed that if you do 
    `amplify init`
followed by
    `amplify add api`
where you set-up both IAM and Cognito auth (email-verification) - this is step (1) above in the section titled 'Reproduction Steps' - then the email gets sent out and all works as expected. The 'email' is checked for verification in the Cognito console.

But if you follow the above with an `amplify auth update` - this is step (2) above in the section titled 'Reproduction Steps' - then it has the issue reported here - email does not get sent out, nothing is checked for verification in the Cognito console and the bug remains as reported.  We have to follow up with an `amplify auth update` in order to create the post confirmation trigger lambda.

**Comment by dorontal** [comment]
**Update: Workaround found!**

At this point I have (a) confirmed that indeed it was the second auth CLI setup command above `amplify auth update` that has caused this issue. 

I also found out that reverting back to an older version of the Amplify CLI is a temporary workaround that no longer creates this issue. Using:

    `Amplify version 4.47.1`

temporarily solves the problems here - i.e. the command `amplify auth update` does not create a locked-up situation in the console where email verification is no longer on, version `4.47.1` works and continues to correctly keep email verification on in the Cognito console...

**Comment by Jordan-Nelson** [comment]
I believe I ran into this issue while adding integration tests for [amplify-flutter](https://github.com/aws-amplify/amplify-flutter). I figured I would share what I experienced in case it is helpful.

We currently use the headless CLI to provision resources for integration tests with a [pretty basic payload](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_auth_cognito/example/tool/add_auth_request.json)

```json
{
  "version": 1,
  "resourceName": "authintegrationtest",
  "serviceConfiguration": {
    "serviceName": "Cognito",
    "userPoolConfiguration": {
      "signinMethod": "USERNAME",
      "requiredSignupAttributes": ["EMAIL", "PHONE_NUMBER"]
    },
    "includeIdentityPool": false
  }
}
```

That payload sets up a user pool with "Which attributes do you want to verify?" set to "No verification" (Note: I am not sure if that is intended - I would have expected it to be set to "Email" with that template). Updating the payload to the below value creates a user pool with "Which attributes do you want to verify?" set to "Email".

```json
{
  "version": 1,
  "resourceName": "authintegrationtest",
  "serviceConfiguration": {
    "serviceName": "Cognito",
    "userPoolConfiguration": {
      "signinMethod": "USERNAME",
      "requiredSignupAttributes": ["EMAIL", "PHONE_NUMBER"],
      "passwordRecovery": {
        "deliveryMethod": "EMAIL",
        "emailMessage": "Your verification code is {####}",
        "emailSubject": "Your verification code"
      }
    },
    "includeIdentityPool": false
  }
}
```

However, we then add a post sign up lambda trigger to auto confirm user's emails (to skip email confirmation in automated tests). The [steps we follow to add the post sign up lambda](https://github.com/aws-amplify/amplify-flutter/blob/main/CONTRIBUTING.md#provision-resources-for-integration-tests) can be found in our contributing docs. After pushing that update, "Which attributes do you want to verify?" is set to "No verification".

The primary issue here is very similar to the one in the original description (updating auth is unexpectedly changing the setting for user attribute confirmation). A potential secondary issue is that without including `"passwordRecovery": {...}` in the payload, the user pool does not require any user attribute confirmation.

**Comment by dorontal** [comment]
With the new version of Amplify CLI 5.1.2 -- this issue has gotten **worse** -- because this new problem I will describe seems extremely related to the one above, I will describe it here, but it is a **new** problem even though the title of this issue fits it perfectly.  This new problem may need a new bug labeled issue and I may open one later for it. It is worth mentioning here.

It is now impossible to set up email-only verification in another way - the 

    `Amplify.Auth().signUp()`

method no longer lets you send the email address as the `username` when it is an email-only sign-up.

It used to always work.  When yous set up for email-only verification and sign-up, you were previously able to supply the email address as the username because the email address **is** the username in that case.

But that use case no longer works.  Here's the code that used to work and no longer works:
```typescript
        return Auth.signUp({
            username: email,
            password,
            attributes: { email }
        });
```

This used to always work. The way in which today it no longer works is this: as soon as you call this function, it returns an error (in the promise) that says:

```
    Username cannot be of email format, since user pool is configured for email alias.
```

in the returned error.  This is worth opening a new issue, which I may do later, but it is related to this issue here because the title / subject of the current issue fits it perfectly.

Any help would be greatly appreciated. Thanks for a great library regardless of these growing pains.

**Comment by iyz91** [comment]
I have this problem as well and once this becomes the case a user cannot receive the verification code to their email on sign up nor request it making Cognito unusable. In addition to the "MFA cannot be turned off if an SMS role is configured" error if trying to disable MFA, if the auto generate sns role is not create or deleted, then one cannot set the MFA to optional even.

![image](https://user-images.githubusercontent.com/72421273/127597520-b0e11320-b749-416f-b23e-1908abc68514.png)

**Comment by iyz91** [comment]
I believe this issue should be prioritized as it makes Cognito completely unusable and it's been open for 24 days as of this writing.

**Comment by iyz91** [comment]
For anyone needing to revert the email verification/recovery settings in the meantime while the console and amplify cli still have their issues, you can use the update-user-pool command of cognito-idp in AWS CLI (or similar) to set the account-recovery-setting and auto-verified-attributes.

`aws cognito-idp update-user-pool --user-pool-id <user pool id> --auto-verified-attributes "email" --account-recovery-setting "RecoveryMechanisms=[{Priority=1,Name=verified_email}]`

(above was using powershell, you may need to adjust for your env)

**Comment by ninjaKris** [comment]
I have been going insane trying to figure out why my email verifications weren't being sent. So far I've been using the amplify-cli to set up auth with a Post Confirmation trigger that adds users to a group. Ended up looking at Cognito, and sure enough, verification was set to None and I can't change it to email because `MFA cannot be turned off if an SMS role is configured`. 

My MFA settings are turned off !!! 😭

**Comment by iyz91** [comment]
@ninjaKris Same here... setting the right settings at the same time via CLI as I commented above does work as an interim solution.

**Comment by dorontal** [comment]
@iyz91 thanks for the workaround but unfortunately I was unable to get it to work on my end.

When I executed the CLI command, it returned nothing (but no error either). I executed it before creating a user with `Auth.signUp()`.

However running this command line did not change things when creating a new user. I still got the same error back from Cognito when calling `Auth.signUp()` as above. The error says:
```
   Username cannot be of email format, since user pool is configured for email alias.
```

Maybe I misunderstood how to use the workaround.

**Comment by iyz91** [comment]
@dorontal So this is the other issue, if the pool is setup using the CLI with the problematic settings, it will change the pool settings to allow username + email combo, instead of the desired email only configuration. Once it's set, it cannot be changed and will throw that error expecting the user to sign up with both a username and email which is what you are seeing. This happens automatically and without any notice... its very annoying. 

So you're solution is to:
1. Teardown the auth stack since it's not what you want and can't change it
2. Recreate the auth stack without specifying groups/triggers so it constructs the pool as desired with email only
3. Then set groups/triggers and call the AWS CLI as needed to fix the other errors mentioned above

**Comment by dorontal** [comment]
@iyz91 thanks very much for this explanation - totally get it now.

**Comment by iyz91** [comment]
@dorontal My pleasure, good luck with your work!

**Comment by dorontal** [comment]
Just tried this again with the new version (5.3.0) and the bug is still there.

This issue is very debilitating -- any development of any app that needs a signed-up user to develop is now impossible.

The error that gets returned when we try to sign up a user with an email address, right now, is:

    "Username cannot be of email format, since user pool is configured for email alias."

The email-only setup fails in two ways: (1) via client code, namely, the following code fails:
```typescript
        return Auth.signUp({
            username: email,
            password,
            attributes: { email }
        });
```
But email-only setup also fails via using the Cognito website console itself:
![email-bug-Screenshot from 2021-08-06 11-11-02](https://user-images.githubusercontent.com/5935957/128532461-1f20064f-9515-465c-9136-9eaee349b6d5.png)

**Comment by dorontal** [comment]
Hello, I am trying to figure out why this bug got closed - the problem reported in this issue is still 100% there for me, as described above. I am still unable to sign up users with email only verification or to set that up in any way that works.

**Comment by jhockett** [comment]
@dorontal the fix was merged and released in [5.6.0](https://www.npmjs.com/package/@aws-amplify/cli/v/5.6.0). Are you still seeing the issue after updating to the latest version?

**Comment by dorontal** [comment]
@jhockett, yes I did try with `5.5.0` and later with `5.6.0` and I do see the same red error reported graphically as in the last screenshot above where it says 'Username cannot be of email format, since user pool is configured for email alias'. Similarly when using `.signUp()` with an email as the username as described above, the same errors saying that username cannot be of email format are reported. Here is my cli `amplify auth update` step that shows the error is still there - the trigger in this case is 'PreSignUp' and in previous cases it was a different trigger but I don't think the trigger type matters to cause this issue, just the fact that there is any trigger at all in the `amplify auth update` step seems to reproduce the issue:
```
Please note that certain attributes may not be overwritten if you choose to use defaults settings.
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (
Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Pre Sign-up
? What functionality do you want to use for Pre Sign-up Create your own module
Successfully added resource landing5d812b31PreSignup locally.
```

**Comment by jhockett** [comment]
I spoke to @akshbhu and it appears there two separate issues. This issue was closed automatically when #7671, one of the needed bug fixes was merged.

The team is working on the second half of the fix and tracking the issue [here](https://github.com/aws-amplify/amplify-cli/issues/7833). It should be fixed in an upcoming release.

**Comment by dorontal** [comment]
Hello, I am trying to figure out why this bug got closed - the problem reported in this issue is still 100% there for me, as described above. I am still unable to sign up users with email only verification or to set that up in any way that works.

**Comment by dorontal** [comment]
@jhockett - with Version 6.0.0 of the Amplify CLI I am no longer seeing this issue - it appears totally fixed. Thank you so much. The same goes for #7671 - version 6.0.0 of the Amplify CLI seems to have closed and fixed both issues.
