### ISSUE TITLE
Error -> amplify update api : TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9186]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.0.1

### Amplify CLI Version

7.6.0

### What operating system are you using?

mac

### Amplify Categories

api

### Amplify Commands

update

### Describe the bug

Getting error after executing `amplify update api` then `Graphql`. I want to update the api default authorization type to AWS_IAM.

```
 amplify update api
? Select from one of the below mentioned services: GraphQL
🛑 Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at displayApiInformation (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts:510:70)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at updateWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts:475:3)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:222:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

### Expected behavior

It should allow to update the api configuration.

### Reproduction steps

1. amplify upgrade
2. amplify update api
3. ERROR

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@hackrx Which version were you upgrading from?

**Comment by hackrx** [comment]
Thanks @ammarkarachi for the follow-up. I am not sure, from the last few days, I think I did upgrade 2-3 times. 
The last upgrade was from 7.5.4. You can check #9150 , in which I faced some issues with the 7.5.4 version, so today I upgraded to the 7.6.0 version.

**Comment by cjihrig** [comment]
Proposed fix in https://github.com/aws-amplify/amplify-cli/pull/9193. In the mean time, if you add `"additionalAuthenticationProviders": []` to your API's section of the `amplify-meta.json` file, it should resolve the issue for you. It will look something like this:

```js
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "API_KEY",
            "apiKeyConfig": {
              "apiKeyExpirationDays": 7,
              "apiKeyExpirationDate": "2021-12-09T20:57:44.352Z",
              "description": ""
            }
          },
          "additionalAuthenticationProviders": []
        },
```

**Comment by hackrx** [comment]
Thanks, @cjihrig, for the quick response. I will update the `amplify-meta.json` file.

**Comment by hackrx** [comment]
Hey @cjihrig, I am still facing this issue, can't able to perform `amplify push`. 
Cli version is `7.6.1`

**Comment by cjihrig** [comment]
@hackrx it looks like you have a few different things going on.

> Getting error after executing amplify update api

This was your original issue. Is this resolved with v7.6.2?

> I can't find the amplify-meta.json file in my amplify project structure.

It should be in your project's `amplify/backend` directory.

> Also, additionalAuthenticationProviders this string doesn't exist in the whole project

That is what is causing the problems. It should be there, and the code is trying to check it. Does the string `authConfig` exist in your project (it should)?

> can't able to perform amplify push

I'm having trouble reproducing this part. If you ran `amplify api update`, it should create the missing `additionalAuthenticationProviders` for you.

**Comment by hackrx** [comment]
Hey @cjihrig , 
>  This was your original issue. Is this resolved with v7.6.2?


Yes it is resolved now.
>  It should be in your project's amplify/backend directory.

![image](https://user-images.githubusercontent.com/54453778/144641232-1c4b0436-15b4-4a86-a6de-e0bf601cce39.png)

Look it is not here.
 
>  That is what is causing the problems. It should be there, and the code is trying to check it. Does the string authConfig exist in your project (it should)?


Yes it there in `amplify/backend/backend-config.json`
![image](https://user-images.githubusercontent.com/54453778/144641683-fdac351d-8e7e-4963-a4b6-36618fd107d7.png)

> I'm having trouble reproducing this part. If you ran amplify api update, it should create the missing additionalAuthenticationProviders for you.

In the above screenshot, you can see, I have `additionalAuthenticationProviders` in the file. But still, facing some issues. 
Can you please check #9203 and #9150 (this one is diff issue though)

**Comment by cjihrig** [comment]
Can you verify in the terminal that the amplify-meta.json does not exist. Sometimes editors hide files.

**Comment by hackrx** [comment]
yes, it is there. 
![image](https://user-images.githubusercontent.com/54453778/144652102-2d454526-29ce-4964-94b9-17d30c9787e9.png)

**Comment by cjihrig** [comment]
OK, so your amplify-meta.json does exist. Does it contain `additionalAuthenticationProviders`?

**Comment by hackrx** [comment]
Yes, it had, I deleted it and made it an empty array. And then it worked.
