### ISSUE TITLE
multienv doesn't work as expected

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#932]
** Which Category is your question related to? **
env

** What AWS Services are you utilizing? **
Amplify

** Provide additional details e.g. code snippets **
I am following steps in https://read.acloud.guru/multiple-serverless-environments-with-aws-amplify-344759e1be08, trying to set up multiple amplify environments that correspond to different git branches.
```
mkdir multienv
cd multienv
git init
(branch: master) amplify init // create an env named prod
(branch: master, env: prod) amplify push
(branch: master, env: prod) git add . && git commit
(branch: master, env: prod) git checkout -b test && amplify init // create an env named staging
(branch: test, env: staging) amplify api add && amplify push
(branch: test, env: staging) git add . && git commit
(branch: test, env: staging) git checkout master && amplify env checkout prod
(branch: master, env: prod) git merge test
(branch: master, env: prod) amplify status // No update shown!
```
I thought the last step should show update in Api category however no update is shown. What goes wrong with my workflow? The only difference between the medium blog and my own experiment being:
- The blog doesn't add and commit, I do
- The blog git push without add and commit, I don't push
Any help? Thank you!

**Comment by kaustavghosh06** [comment]
@YikSanChan Could you please try out this flow again with the latest version of the CLI which we published. I beleive this is somewhat tied to your previous issue -> #931

**Comment by kaustavghosh06** [comment]
@YikSanChan Let me know if you're still seeing issue. Please feel free to re-open if you're still seeing this.

**Comment by YikSanChan** [comment]
@kaustavghosh06 I cannot reopen the issue that is not closed by myself.

The problem is still there. I tried with amplify-cli version 1.1.6. I believe you can easily reproduce

**Comment by kaustavghosh06** [comment]
@YikSanChan I see the problem. 
So you would have to first `git merge test` and then `amplify env checkout prod` or if you are going through your  flow you've mentioned above, after you do a `git merge test`, you would have to again run `amplify env checkout prod` for the CLI to form the metadata that you've merged from the test branch. I would recommend doing the first former.

**Comment by YikSanChan** [comment]
Thanks, @kaustavghosh06 I tried the former one and it works. Can you explain why? What files does `amplify env checkout` checks to determined whether there are amplify categories update?

**Comment by kaustavghosh06** [comment]
@YikSanChan So after you merge your backend/ changes from your git branch, when you run `amplify env  checkout` it takes a look at your directory structure and modifies files like the `backend/amplify-meta.json` file based on the merged directory structure. The CLI commands look at the `backend/amplify-meta.json` file to display output for commands like `amplify status`
