### ISSUE TITLE
Not Authorized to access createUser on type User

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9365]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.3

### What operating system are you using?

mac

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

I want to create a `user` doc when user confirms his account using `postConfirmation` trigger, but I am facing this error: 

```
{
  "data": {
    "createUser": null
  },
  "errors": [
    {
      "path": [
        "createUser"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 9,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access createUser on type User"
    }
  ]
}
```
But  using `amplify status api -acm User   ` , it gives, below result, which clearly states that IAM must be allowed for any kind of operations:
```
userPools:owner:owner
  ┌─────────┬────────┬───────┬────────┬────────┐
  │ (index) │ create │ read  │ update │ delete │
  ├─────────┼────────┼───────┼────────┼────────┤
  │   id    │ false  │ true  │ false  │ false  │
  │  name   │ false  │ true  │  true  │ false  │
  │  owner  │ false  │ false │ false  │ false  │
  │  email  │  true  │ true  │  true  │  true  │
  │  posts  │  true  │ true  │  true  │  true  │
  └─────────┴────────┴───────┴────────┴────────┘
userPools:private
  ┌─────────┬────────┬───────┬────────┬────────┐
  │ (index) │ create │ read  │ update │ delete │
  ├─────────┼────────┼───────┼────────┼────────┤
  │   id    │ false  │ true  │ false  │ false  │
  │  name   │ false  │ true  │ false  │ false  │
  │  owner  │ false  │ false │ false  │ false  │
  │  email  │ false  │ false │ false  │ false  │
  │  posts  │  true  │ true  │  true  │  true  │
  └─────────┴────────┴───────┴────────┴────────┘
iam:private
  ┌─────────┬────────┬──────┬────────┬────────┐
  │ (index) │ create │ read │ update │ delete │
  ├─────────┼────────┼──────┼────────┼────────┤
  │   id    │  true  │ true │  true  │  true  │
  │  name   │  true  │ true │  true  │  true  │
  │  owner  │  true  │ true │  true  │  true  │
  │  email  │  true  │ true │  true  │  true  │
  │  posts  │  true  │ true │  true  │  true  │
  └─────────┴────────┴──────┴────────┴────────┘
```

And the mutation is: 
```
mutation MyMutation2 {
  createUser(input: {id:"COGNITO_USERNAME" ,name: "testUser", email:"test@gmail.com","owner":"COGNITO_USERNAME",}) {
    id
    name
  }
}
```
I am passing owner as input, so that the account owner can update his name or do other operations later easily. for eg. update name, etc.

where `COGNITO_USERNAME` is `uuidV4`, I don't want to call this query from client side, that's why I am doing this from cognito trigger.
Also IAM is not able to perform any update operation.
I don't want to stick with api key authentication, because I don't want to remember the expiry date, also with flutter if we are using api key, then it  by default sends all query/mutation requests using API  key only.

### Expected behavior

Appsync should allow IAM to perfrom CRUD operation if mentioned as 
```
  { allow: private, provider: iam }
```
In amplify, I can confirm that I have cognitoUserPools as default and IAM as authentication provider.

### Reproduction steps

1. Create basic model
2. amplify migrate api
3. add auth directives with owner and IAM
4. do some operation using iam

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type User
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      { allow: owner, provider: userPools }
      { allow: private, provider: userPools }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID!  @auth(
    rules: [
      { allow: owner, provider: userPools, operations:[read] }
      { allow: private, provider: userPools, operations: [read] }
      { allow: private, provider: iam }
    ]
  )
  name: String!  @auth(
    rules: [
      { allow: owner, provider: userPools, operations:[read,update] }
      { allow: private, provider: userPools, operations: [read] }
      { allow: private, provider: iam }
    ]
  )
  owner: String!  @auth(
    rules: [
      { allow: private, provider: iam }
    ]
  )
  email: String!  @auth(                                     # --> don't want to allow other authenticated users instead of user and Iam for  
                                                                             #         crud operation
    rules: [
      { allow: owner, provider: userPools }
      { allow: private, provider: iam }
    ]
  )
  posts: [Post] @hasMany(indexName: "byUser", fields: ["id"])
}

type Post
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      { allow: owner, provider: userPools }
      { allow: private, provider: userPools, operations: [read] }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID!
  title: String!
  userID: ID! @index(name: "byUser")
  user: User @belongsTo(fields: ["userID"])
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}

type Comment
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      { allow: owner, provider: userPools }
      { allow: private, provider: userPools, operations: [read] }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  post: Post @belongsTo(fields: ["postID"])
  content: String!
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by marcvberg** [comment]
Could you check the contents of your `custom-roles.json`?
Per these instructions here: https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console

I'm wondering if your role has access to AppSync but is not configured to be allowed within the resolvers

**Comment by hackrx** [comment]
hey @marcvberg, `custom-roles.json` does not exist in the `amplify/backend/api/$apiName`, it should auto-generate if I am choosing IAM as auth provider for graphql api. 
can you please tell me, what should I add into role array: 
```
{
  "adminRoleNames": ["<YOUR_IAM_USER_OR_ROLE_NAME>"]
}
```
so that it will allow all lambda functions to execute app sync queries?
Thanks 🙂

**Comment by marcvberg** [comment]
You won't need the full ARN, just whatever the name of the role is i.e. "Admin" in the list
We can look into detecting private IAM authorization to generate that file

Let me know if that resolves the issue for you!

**Comment by hackrx** [comment]
can you please tell me clearly, where I need to grab this? 
> You won't need the full ARN, just whatever the name of the role is i.e. "Admin" in the list

where can I get this role? in IAM? and did it was automatically created by amplify?
To be honest, I am pretty new to amplify 🙂 , can you please guide me a little?

**Comment by hackrx** [comment]
I fixed it: 
```
{
  "adminRoleNames": ["hackrx","testuser","blogLambdaRole0axx64b8-testblog"]
}
```

**Comment by acusti** [comment]
@marcvberg thanks for your helpful instructions in this issue thread! when i check the **Use IAM authorization within the AppSync console** instructions in the documentation you linked to, i see this instructions:

> IAM-based `@auth` rules are scoped down to only work with Amplify-generated IAM roles. To access the GraphQL API with IAM authorization within your AppSync console, you need to explicitly allow list the IAM user's name by adding them to `amplify/backend/api/<your-api-name>/custom-roles.json`. (Create the custom-roles.json file if it doesn't exist). Append the adminRoleNames array with the IAM role or user names:
```json
{
  "adminRoleNames": ["<YOUR_IAM_USER_OR_ROLE_NAME>"]
}
```

i created a `custom-roles.json` and added the role names for my custom cognito lambdas, so that’s all good to go. however, i still cannot use the AppSync console any more to run queries and mutations using the IAM authorization as i did before migrating to GQL transformer v2, and i have no idea what the IAM user or role name string should be from within the AppSync console. how can i find that out? or is it the same string for everyone and i can just append that to the array?

**Comment by rafaelfaria** [comment]
hey, @marcvberg I am having the same issue. I added "admin" at `adminRoleNames`, a user that has admin privileges from IAM for testing, and i still get unauthorized.

Is there any difference from when you are testing locally? 

Here what I have:

schema:
```

type Alert @model
  @auth(
    rules: [
      { allow: owner },
      { allow: private, provider: iam },
    ]
  )
  {
  id: ID!
  status: AlertStatus!
  type: AlertType!
  price: Float!
  tokenName: String!
  tokenAddress: String!
  tokenSymbol: String!
  triggeredDate: String
}
```

custom-roles.json
```
{
  "adminRoleNames": ["lambda-graphql", "admin"]
}
```

and to make the call I use this (just copying the part of the request):

```

async function graphQLRun(aQuery, aVariables) {
  try {
    let httpReq = createSignedReq(aQuery, aVariables);
    let data = await fetchData(httpReq);
  } catch(err) { console.log(err) }

} 

function createSignedReq(aQuery, aVariables) {
  const graphQlEndpoint = getGraphQlEndpoint();
  const endpoint = new UrlParse(graphQlEndpoint).hostname.toString();

  const req = new AWS.HttpRequest(graphQlEndpoint, process.env.REGION);  // change this to your region
  req.method = 'POST';
  req.path = '/graphql';
  req.headers.host = endpoint;
  req.headers['Content-Type'] = 'application/json; charset=UTF-8';

  let queryData = {
    query: print(gql(aQuery)),
  };

  if (aVariables) {
    queryData.variables = aVariables;
  }

  req.body = JSON.stringify(queryData);

  const signer = new AWS.Signers.V4(req, 'appsync', true);
  signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate());

  let signedReq = {
    ...req.endpoint,
    ...req,
    host: endpoint,
    timeout: 30000,
  };

  return signedReq;
}

function fetchData(httpReq) {
  return new Promise(async (resolve, reject) => {
    let received = '';

    // Choose the proper protocol to make the call to the graphql server
    // A mock server supports only http.
    const requestProtocol = httpReq.endpoint.protocol === "http:" ? http : https;

    const httpRequest = requestProtocol
      .request(httpReq, (result) => {
        result
          .on('data', (data) => {
            received += data;
          })
          .on('end', function () {
            try {
              let r = JSON.parse(received.toString());
              if (r.hasOwnProperty('errors')) {
                reject(r.errors[0].message);
              } else {
                resolve(r);
              }
            } catch(err) {
              console.log(err);
            }
          });
      })
      .on('timeout', function () {
        httpRequest.destroy(new Error('timeout'));
      })
      .on('error', (e) => {
        reject(e.message);
      });

    httpRequest.write(httpReq.body);
    httpRequest.end();
  });
}

function getGraphQlEndpoint() {
  let k = Object.keys(process.env).filter((key) => {
    if (key.indexOf('GRAPHQLAPIENDPOINTOUTPUT') !== -1) {
      return true;
    }
  });
  let endpoint;
  if (k.length > 0) {
    endpoint = process.env[k[0]];
  }

  return endpoint;
}

```


not sure what else I can do. I have been losing hair for days trying to make this work, and this only started happening once i moved to transformer 2. 

Appreciate the help.

**Comment by James1218** [comment]
I'm having the same issue. I added the lambda role, then the lambda function can access graphql API. But I cannot get Appsync console to access the graphql API. It's unauthorized. What role should I put into `custom-role.json` in order to grant Appsync console access?

**Comment by movingelectrons** [comment]
also having a issue with this tried tons of things stuck for hours now... grr
