### ISSUE TITLE
There is an error when creating an api with transformer version 2.

### ISSUE THREAD

**Issue by rnrnstar2** [aws-amplify/amplify-cli#9372]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v14.17.4

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I created a new app in the amplify console and started amplify studio.
So I created a model and deployed it.
For model, I added only the model with the name added.
The deployment is complete and the backend has been pulled locally.

I edited the local schema.graqhql file.

Then I ran amplify push.
Then an error will occur.
This is the attached log file.
[newapperror.log](https://github.com/aws-amplify/amplify-cli/files/7773497/newapperror.log)

Do you know the cause of this error?

### Expected behavior

Backend construction can be done normally

### Reproduction steps

1. Create a new app with amplify console
2. Start the growing studio.
3. Create and deploy a model with a minimal name.
4. Pulled locally.
5. Edit the local schema.graqhql file.
6. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Owner @model @auth(rules: [{ allow: public }]) {
  id: ID!
  name: String
  email: AWSEmail
  sub: String
  customerID: String
  trial: Boolean
  stripeAccount: String
  stripeParentAccount: String
  Tenants: [Tenant] @hasMany(indexName: "byOwner", fields: ["id"])
  TimeLines: [TimeLine] @hasMany(indexName: "byOwner", fields: ["id"])
}

type Staff @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerList: [String]
  tenantID: ID @index(name: "byTenant")
  lineID: ID
  name: String
  s3ImgKey: String
  sub: String
  appealPoint: String
  sns: SNS
  profile: Profile
  allMenu: Boolean
  canSelect: Boolean
  selectionFee: Int
  sort: Int
  capacity: Int
  ShiftPatterns: [ShiftPattern] @hasMany(indexName: "byStaff", fields: ["id"])
  Shifts: [Shift] @hasMany(indexName: "byStaff", fields: ["id"])
  ShiftBreaks: [ShiftBreak] @hasMany(indexName: "byStaff", fields: ["id"])
  Reservations: [Reservation] @hasMany(indexName: "byStaff", fields: ["id"])
  TimeLines: [TimeLine] @hasMany(indexName: "byStaff", fields: ["id"])
  UserKartes: [UserKarte] @hasMany(indexName: "byStaff", fields: ["id"])
  MenuCoupons: [MenuCoupon] @manyToMany(relationName: "StaffMenuCoupon")
}

type User @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  lineID: ID @index(name: "byLineID", queryField: "userByLineID", sortKeyFields: ["lastVisitDate"])
  officiallineID: ID @index(name: "byOfficialLine")
  addfriendID: ID @index(name: "byAddFriend")
  userstatusID: ID @index(name: "byUserStatus")
  richmenuID: ID @index(name: "byRichMenu")
  name: String
  description: String
  sns: SNS
  profile: Profile
  lastVisitDate: AWSDateTime
  from: String
  score: Int
  blocked: Boolean
  Visits: [Visit] @hasMany(indexName: "byUser", fields: ["id"])
  Reservations: [Reservation] @hasMany(indexName: "byUser", fields: ["id"])
  SendMessages: [SendMessage] @hasMany(indexName: "byUser", fields: ["id"])
  Messages: [Message] @hasMany(indexName: "byUser", fields: ["id"])
  UserMemos: [UserMemo] @hasMany(indexName: "byUser", fields: ["id"])
  UserKartes: [UserKarte] @hasMany(indexName: "byUser", fields: ["id"])
  UserInfos: [UserInfo] @hasMany(indexName: "byUser", fields: ["id"])
  UserScenarios: [UserScenario] @hasMany(indexName: "byUser", fields: ["id"])
  UserCampaigns: [UserCampaign] @hasMany(indexName: "byUser", fields: ["id"])
  UserLabels: [UserLabel] @manyToMany(relationName: "UserUserLabel")
}

type LiffUser @model @auth(rules: [{ allow: public }]) {
  id: ID!
  lineID: ID
  name: String
  sub: String
  profile: Profile
  s3AlbumKey: String
  Reservations: [Reservation] @hasMany(indexName: "byLiffUser", fields: ["id"])
}

type OfficialLine @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  basicId: String
  premiumId: String
  pictureUrl: AWSURL
  name: String
  channelSecret: String
  channelAccessToken: String!
  AddFriends: [AddFriend] @hasMany(indexName: "byOfficialLine", fields: ["id"])
  Scenarios: [Scenario] @hasMany(indexName: "byOfficialLine", fields: ["id"])
  SendMessages: [SendMessage] @hasMany(indexName: "byOfficialLine", fields: ["id"])
  Segments: [Segment] @hasMany(indexName: "byOfficialLine", fields: ["id"])
  Messages: [Message] @hasMany(indexName: "byOfficialLine", fields: ["id"])
  Users: [User] @hasMany(indexName: "byOfficialLine", fields: ["id"])
  UserScenarios: [UserScenario] @hasMany(indexName: "byOfficialLine", fields: ["id"])
}

type Tenant @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID! @index(name: "byOwner")
  officiallineID: ID
  subscriptionID: String
  name: String
  phone: AWSPhone
  address: String
  appealPoint: String
  s3ImgKey: String
  s3AlbumKey: String
  open: Open
  separate: Int
  period: Int
  deadline: Int
  cancelDeadline: Int
  status: Boolean
  completed: Boolean
  plan: TenantPlan
  options: [TenantOption]
  triggers: [Trigger]
  sns: SNS
  theme: Theme
  reserveRequired: ReserveRequired
  Menus: [Menu] @hasMany(indexName: "byTenant", fields: ["id"])
  MenuCoupons: [MenuCoupon] @hasMany(indexName: "byTenant", fields: ["id"])
  MenuCouponLabels: [MenuCouponLabel] @hasMany(indexName: "byTenant", fields: ["id"])
  RichMenus: [RichMenu] @hasMany(indexName: "byTenant", fields: ["id"])
  Actions: [Action] @hasMany(indexName: "byTenant", fields: ["id"])
  Reservations: [Reservation] @hasMany(indexName: "byTenant", fields: ["id"])
  MessageTemplates: [MessageTemplate] @hasMany(indexName: "byTenant", fields: ["id"])
  Campaigns: [Campaign] @hasMany(indexName: "byTenant", fields: ["id"])
  Visits: [Visit] @hasMany(indexName: "byTenant", fields: ["id"])
  SpecificHolidays: [SpecificHoliday] @hasMany(indexName: "byTenant", fields: ["id"])
  Staff: [Staff] @hasMany(indexName: "byTenant", fields: ["id"])
  Shift: [Shift] @hasMany(indexName: "byTenant", fields: ["id"])
  TimeLines: [TimeLine] @hasMany(indexName: "byTenant", fields: ["id"])
  Users: [User] @hasMany(indexName: "byTenant", fields: ["id"])
  UserLabels: [UserLabel] @hasMany(indexName: "byTenant", fields: ["id"])
  UserStatuss: [UserStatus] @hasMany(indexName: "byTenant", fields: ["id"])
  UserInfoCategorys: [UserInfoCategory] @hasMany(indexName: "byTenant", fields: ["id"])
}

type Reservation @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
    @index(name: "byTenant", queryField: "reservationByTenantID", sortKeyFields: ["start"])
  userID: ID @index(name: "byUser")
  liffuserID: ID @index(name: "byLiffUser")
  staffID: ID @index(name: "byStaff", queryField: "reservationByStaffID", sortKeyFields: ["start"])
  start: AWSDateTime
  end: AWSDateTime
  actualStart: AWSDateTime
  actualEnd: AWSDateTime
  memo: String
  status: ReservationStatus
  type: ReservationType
  name: String
  selected: Boolean
  Menus: [Menu] @manyToMany(relationName: "MenuReservation")
  MenuCoupons: [MenuCoupon] @manyToMany(relationName: "MenuCouponReservation")
}

type Menu @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  name: String
  time: Int
  price: Int
  description: String
  s3ImgKey: String
  sort: Int
  publish: Boolean
  type: MenuType
  MenuCoupons: [MenuCoupon] @manyToMany(relationName: "MenuMenuCoupon")
  Reservations: [Reservation] @manyToMany(relationName: "MenuReservation")
}

type MenuCoupon @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  name: String
  time: Int
  price: Int
  description: String
  s3ImgKey: String
  sort: Int
  publish: Boolean
  type: MenuCouponType
  start: AWSDate
  end: AWSDate
  Menus: [Menu] @manyToMany(relationName: "MenuMenuCoupon")
  MenuCouponLabels: [MenuCouponLabel] @manyToMany(relationName: "MenuCouponMenuCouponLabel")
  Reservations: [Reservation] @manyToMany(relationName: "MenuCouponReservation")
  Staffs: [Staff] @manyToMany(relationName: "StaffMenuCoupon")
}

type ShiftPattern @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerList: [String]
  tenantID: ID
  staffID: ID @index(name: "byStaff")
  start: AWSTime
  end: AWSTime
  weekDays: [Int]
}

type Shift @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerList: [String]
  tenantID: ID @index(name: "byTenant")
  staffID: ID @index(name: "byStaff")
  start: AWSDateTime
  end: AWSDateTime
}

type ShiftBreak @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerList: [String]
  tenantID: ID
  staffID: ID @index(name: "byStaff")
  start: AWSDateTime
  end: AWSDateTime
}

type SpecificHoliday @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  date: AWSDate
}

type Action @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  isTemplate: Boolean
  tagAction: [AWSJSON]
  statusAction: [AWSJSON]
  richMenuAction: [AWSJSON]
  userInfoAction: [AWSJSON]
  templateDataList: [TemplateData]
  scoreAction: Int
  scenarioID: ID
  campaignID: ID
}

type RichMenu @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  richMenuId: String
  publish: Boolean
  name: String
  s3ImgKey: String
  chatBarText: String
  selected: Boolean
  size: RichMenuSize
  areas: [RichMenuArea]
  actions: [AWSJSON]
  Users: [User] @hasMany(indexName: "byRichMenu", fields: ["id"])
}

type AddFriend @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  officiallineID: ID @index(name: "byOfficialLine")
  actionID: ID
  basicId: String
  title: String
  Users: [User] @hasMany(indexName: "byAddFriend", fields: ["id"])
}

type Segment @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  officiallineID: ID @index(name: "byOfficialLine")
  actionID: ID
  status: Boolean
  expirydate: AWSDateTime
  executionArn: String
  filterList: [Filter]
  SendMessages: [SendMessage] @hasMany(indexName: "bySegment", fields: ["id"])
  UserScenarios: [UserScenario] @hasMany(indexName: "bySegment", fields: ["id"])
}

type Campaign @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  actionID: ID
  title: String
  publish: Boolean
  type: CampaignType
  description: String
  s3ImgKey: String
  perPerson: Int
  limitAmount: Int
  redirectLink: AWSURL
  UserCampaigns: [UserCampaign] @hasMany(indexName: "byCampaign", fields: ["id"])
}

type UserCampaign @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  userID: ID @index(name: "byUser")
  campaignID: ID @index(name: "byCampaign")
  actionID: ID
}

type Scenario @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  officiallineID: ID @index(name: "byOfficialLine")
  name: String
  scenarioDataList: [ScenarioData]
  type: ScenarioType
  publish: Boolean
  UserScenarios: [UserScenario] @hasMany(indexName: "byScenario", fields: ["id"])
}

type UserScenario @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  addfriendID: ID
  campaignID: ID
  officiallineID: ID @index(name: "byOfficialLine")
  userID: ID @index(name: "byUser")
  scenarioID: ID @index(name: "byScenario")
  segmentID: ID @index(name: "bySegment")
  triggerType: TriggerType
  executionArn: String
  scenarioDataID: String
  status: Boolean
  SendMessages: [SendMessage] @hasMany(indexName: "byUserScenario", fields: ["id"])
}

type SendMessage @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  addfriendID: ID
  campaignID: ID
  scenarioID: ID
  officiallineID: ID @index(name: "byOfficialLine")
  userID: ID @index(name: "byUser")
  segmentID: ID @index(name: "bySegment")
  userscenarioID: ID @index(name: "byUserScenario")
  result: Boolean
  status: Boolean
  triggerType: TriggerType
  executionArn: String
  expirydate: AWSDateTime
  templateDataList: [TemplateData]
}

type MessageTemplate @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  templateData: [TemplateData]
}

type Message @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  officiallineID: ID @index(name: "byOfficialLine")
  userID: ID @index(name: "byUser")
  lineID: ID
  messageID: ID
  message: String
  type: MessageType
  direction: String
  payload: AWSJSON
}

type Visit @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  userID: ID @index(name: "byUser")
  campaignID: ID
  sendmessageID: ID
  reservationID: ID
  date: AWSDateTime
  isNew: Boolean
  UserKartes: [UserKarte] @hasMany(indexName: "byVisit", fields: ["id"])
}

type TimeLine @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID @index(name: "byOwner")
  tenantID: ID @index(name: "byTenant")
  staffID: ID @index(name: "byStaff")
  title: String
  description: String
  isChange: Boolean
  changeBy: DataModel
  changeAt: DataModel
  changeMethod: ChangeMethod
}

type UserMemo @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  userID: ID @index(name: "byUser")
  memo: String
  s3FileKey: String
}

type UserKarte @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  userID: ID @index(name: "byUser")
  visitID: ID @index(name: "byVisit")
  staffID: ID @index(name: "byStaff")
  date: AWSDate
  S3Album: String
  memo: String
  starRating: Int
}

type UserInfoCategory @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  name: String
  type: UserInfoType
  selectList: [String]
  UserInfos: [UserInfo] @hasMany(indexName: "byUserInfoCategory", fields: ["id"])
}

type UserInfo @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID
  userID: ID @index(name: "byUser")
  userInfoCategoryID: ID @index(name: "byUserInfoCategory")
  type: UserInfoType
  text: String
  select: String
  s3FileKey: String
  s3ImgKey: String
  date: AWSDate
}

type MenuCouponLabel @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  name: String
  color: String
  MenuCoupons: [MenuCoupon] @manyToMany(relationName: "MenuCouponMenuCouponLabel")
}

type UserLabel @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  name: String
  color: String
  Users: [User] @manyToMany(relationName: "UserUserLabel")
}

type UserStatus @model @auth(rules: [{ allow: public }]) {
  id: ID!
  ownerID: ID
  tenantID: ID @index(name: "byTenant")
  name: String
  color: String
  users: [User] @hasMany(indexName: "byUserStatus", fields: ["id"])
}

type Profile {
  email: AWSEmail
  displayName: String
  pictureUrl: AWSURL
  given_name: String
  middle_name: String
  family_name: String
  given_name_kana: String
  middle_name_kana: String
  family_name_kana: String
  full_name: String
  full_name_kana: String
  gender: Gender
  age: Int
  birthdate: AWSDate
  phone_number: AWSPhone
  address: Address
  statusMessage: String
  language: String
}

type Address {
  postal_code: String
  region: String
  locality: String
  street_address: String
  country: String
}

type Trigger {
  type: TriggerType
  actionID: ID
  dayAfter: Int
  time: AWSTime
  timeAfter: Int
  score: Int
}

type SNS {
  hashtag: String
  instagram: String
  twitter: String
  tiktok: String
}

type TemplateData {
  title: String
  message: AWSJSON
}

type Filter {
  type: FilterType
  conditionType: ConditionType
  isNot: Boolean
  idList: [ID]
  userInfoCategoryID: ID
  startDate: AWSDate
  endDate: AWSDate
  text: String
}

type ScenarioData {
  id: ID
  actionID: ID
  dayAfter: Int
  time: AWSTime
  timeAfter: Int
}

type TextField {
  title: String
  type: String
  unit: String
  placeholder: String
  multiple: Boolean
  min: Int
  max: Int
}

type SelectField {
  type: String
  multiple: Boolean
  options: [Option]
}

type Option {
  name: String
  s3ImgKey: String
}

type DataModel {
  model: String
  modelID: String
  name: String
}

type Open {
  SundayStart: String
  SundayEnd: String
  MondayStart: String
  MondayEnd: String
  TuesdayStart: String
  TuesdayEnd: String
  WednesdayStart: String
  WednesdayEnd: String
  ThursdayStart: String
  ThursdayEnd: String
  FridayStart: String
  FridayEnd: String
  SaturdayStart: String
  SaturdayEnd: String
  holiday: [Int]
  calendarStart: String
  calendarEnd: String
}

type Theme {
  mainColor: String
  mainTextColor: String
  subColor: String
  subTextColor: String
  backgroundColor: String
}

type ReserveRequired {
  name: Boolean
  email: Boolean
  phone: Boolean
  birthdate: Boolean
  gender: Boolean
  message: Boolean
  address: Boolean
  userInfoCategoryIDList: [String]
}

type RichMenuSize {
  width: Int
  height: Int
}

type RichMenuArea {
  bounds: AWSJSON
  action: AWSJSON
}

enum ScenarioType {
  BIRTHDAY
}

enum TriggerType {
  VISIT
  RESERVE
  RESERVEDATE
  ADDFRIEND
  EXISTINGFRIEND
}

enum MenuType {
  OPTION
  SECRET
}

enum TenantPlan {
  FREE
  LIGHT
  STANDARD
  PREMIUM
}

enum TenantOption {
  CRM
  RESERVATION
  ANALYTICS
  CHAT
  SCENARIO
  FORM
  RICHMENU
}

enum MenuCouponType {
  NEW
  REPEAT
  LIMITED
  SECRET
}

enum UserInfoType {
  TEXT
  DATE
  SELECT
  IMAGE
  PDF
}

enum CampaignType {
  VISIT
  OPEN
  COUPON
}

enum MessageType {
  TEXT
  IMAGE
  S3IMAGE
  CAMPAIGN
  SEPARATOR
}

enum ReservationStatus {
  ACTIVE
  CANCEL
  CANCELBYSTORE
  CANCELBYUSER
  HOLD
  SUCCESS
}

enum ReservationType {
  LINE
  TELL
  OTHER
}

enum FilterType {
  TAG
  STATUS
  USERINFO
  ADDFRIEND
  LASTVISITDATE
}

enum ConditionType {
  AND
  OR
  EQUAL
  INCLUDE
  EXISTS
  CONTAINS
}

enum Gender {
  MALE
  FEMALE
  CUSTOM
}

enum ChangeMethod {
  CREATE
  READ
  UPDATE
  DELETE
  SUCCESS
  FAIL
}


```

</details>

### Log output

<details>

```
# Put your logs below this line
[amplify-cli-2021-12-24.log](https://github.com/aws-amplify/amplify-cli/files/7773493/amplify-cli-2021-12-24.log)

```

</details>

**Comment by ammarkarachi** [comment]
@rnrnstar2 It looks like there is a cloudformatin error from AppSync 
```bash
Reason: Schema is currently being altered, please wait until that is complete. (Service: AmazonDeepdish; Status Code: 409; Error Code: ConcurrentModificationException; Request ID: 8883fab0-a9da-4422-92f7-cf12f4765a47; Proxy: null)
```
Pasting this here for reference.

**Comment by rnrnstar2** [comment]
@ammarkarachi 

thank you.
The attached error is displayed every time.

I am running this command "amplify push" for the first time.
Is the error an internal cloudgormation error?

Is there a problem with schema.graphql?

**Comment by MattJBrowning** [comment]
Also having this issue. I've found that it happens mainly when adding multiple fields that use relationship directives. If you only add one new type, or relationship per push it usually goes through without a hitch. When trying to do everything at once, it's a gamble.

**Comment by edwardfoyle** [comment]
Hi @rnrnstar2 and @MattJBrowning I've confirmed that this is a service issue that occurs when attaching many resolver functions to a single data source. One potential workaround that we can investigate is adding a `DependsOn` block to each resolver function to force them to be created in serial. I've also filed a ticket with the service team to see if this can be fixed in the service as well.

Unfortunately in the meantime there's not much that you can do besides try deploying your schema in smaller chunks. ie. add a few models, deploy, add a few more, deploy again, etc. I'm sorry it's such a tedious workaround but hopefully it will unblock you until we can get to a more suitable solution.

**Comment by MattJBrowning** [comment]
@edwardfoyle Thanks for confirming the bug! Glad there is a workaround, even if it's not the most optimal.

**Comment by MattJBrowning** [comment]
Any update on this issue? Using Amplify CI to deploy to hosting seemed to work earlier, now it fails it seems 100% of the time, regardless how small the changes are, can't push any updates from the CLI without it failing

Is this a widespread issue? How would I configure DependsOn, at this point I have my entire development team sitting idle because we can't develop. Considering migrating away from Amplify due to the issue.

**Comment by undefobj** [comment]
@MattJBrowning @rnrnstar2 we have rolled out a change in AppSync that should address this issue from the backend. Can you try again and let us know if you're still having trouble or if the issue is now resolved?

**Comment by cjihrig** [comment]
I'm going to close this, as we believe it is resolved, but feel free to comment if you are still encountering the issue.

**Comment by AWSZM** [comment]
> I'm going to close this, as we believe it is resolved, but feel free to comment if you are still encountering the issue.

Hello, AWS SSMT received a Twitter contact from a user experiencing this issue still. May we kindly re-open this?

User: https://twitter.com/rkustner/status/1502382116297969664
