### ISSUE TITLE
npm i -g @aws-amplify/cli does not install

### ISSUE THREAD

**Issue by Nicktho** [aws-amplify/amplify-cli#9681]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.3.0

### Amplify CLI Version

v7.6.15

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

When installing `@aws-amplify/cli` globally, `npm` cannot resolve the dependency tree.

### Expected behavior

`@aws-amplify/cli` installs correctly.

### Reproduction steps

npm i -g @aws-amplify/cli 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
❯ npm i -g @aws-amplify/cli 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/@aws-amplify/cli/node_modules/graphql
npm ERR!   graphql@"^14.5.8" from @aws-amplify/amplify-category-api@1.2.6
npm ERR!   node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api
npm ERR!     @aws-amplify/amplify-category-api@"1.2.6" from @aws-amplify/cli@7.6.15
npm ERR!     node_modules/@aws-amplify/cli
npm ERR!       @aws-amplify/cli@"*" from the root project
npm ERR!     @aws-amplify/amplify-category-api@"1.2.6" from amplify-container-hosting@2.4.17
npm ERR!     node_modules/@aws-amplify/cli/node_modules/amplify-container-hosting
npm ERR!       amplify-container-hosting@"2.4.17" from @aws-amplify/cli@7.6.15
npm ERR!       node_modules/@aws-amplify/cli
npm ERR!         @aws-amplify/cli@"*" from the root project
npm ERR!   graphql@"^14.5.8" from @aws-amplify/graphql-auth-transformer@0.7.1
npm ERR!   node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer
npm ERR!     @aws-amplify/graphql-auth-transformer@"0.7.1" from @aws-amplify/cli@7.6.15
npm ERR!     node_modules/@aws-amplify/cli
npm ERR!       @aws-amplify/cli@"*" from the root project
npm ERR!     @aws-amplify/graphql-auth-transformer@"0.7.1" from amplify-provider-awscloudformation@5.9.1
npm ERR!     node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation
npm ERR!       amplify-provider-awscloudformation@"5.9.1" from @aws-amplify/cli@7.6.15
npm ERR!       node_modules/@aws-amplify/cli
npm ERR!         @aws-amplify/cli@"*" from the root project
npm ERR!       3 more (@aws-amplify/amplify-category-api, ...)
npm ERR!     1 more (@aws-amplify/graphql-relational-transformer)
npm ERR!   65 more (amplify-app, amplify-codegen, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm ERR! node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/node_modules/@graphql-codegen/visitor-plugin-common/node_modules/relay-compiler
npm ERR!   relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.1
npm ERR!   node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/node_modules/@graphql-codegen/visitor-plugin-common/node_modules/@graphql-tools/relay-operation-optimizer
npm ERR!     @graphql-tools/relay-operation-optimizer@"^6.3.7" from @graphql-codegen/visitor-plugin-common@2.5.2
npm ERR!     node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/node_modules/@graphql-codegen/visitor-plugin-common
npm ERR!       @graphql-codegen/visitor-plugin-common@"^2.5.1" from amplify-codegen-appsync-model-plugin@1.24.4
npm ERR!       node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/tho/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tho/.npm/_logs/2022-02-03T01_05_24_523Z-debug.log

```

</details>

**Comment by KevinBenjamin** [comment]
I'm getting this too.

**Comment by KevinBenjamin** [comment]
@josefaidt, This looks similar to [this issue](https://github.com/aws-amplify/amplify-cli/issues/9544)

**Comment by cjihrig** [comment]
I agree with @KevinBenjamin here.

I was able to reproduce the error on Node 16.3.0 as originally reported. However, upgrading npm fixed the issue for me.

**Comment by Nicktho** [comment]
I can confirm upgrading `npm` from `7.15.1` to `7.24.2` resolved the issue and I am now able to install `@aws-amplify/cli@7.6.15`

**Comment by josefaidt** [comment]
Hey @Nicktho and @KevinBenjamin :wave: glad to hera y'all are unblocked 🙌 . Closing as the issue is now resolved 🙂

**Comment by KevinBenjamin** [comment]
This is not resolved for me.  It still fails with npm `7.24.2`.  This is with node `14.4.0`. With higher versions of node, using npm `8.1.4`, it also does not work.
I'm trying to upgrade from `@aws-amplify/cli@6.1.1`.

**Comment by julien-tamade** [comment]
Running into the same issue with npm 8.5.0. Any solution?

**Comment by mvpdevs42** [comment]
Same issue
