### ISSUE TITLE
Problem with pipenv when deploying

### ISSUE THREAD

**Issue by awhillas** [aws-amplify/amplify-cli#9948]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.19.0

### Amplify CLI Version

7.6.23

### What operating system are you using?

Windows > WSL2 > Ubuntu20.04

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No none

### Amplify Categories

api

### Amplify Commands

add, push

### Describe the bug

1. I do a simple `amplify api add` go through all the business and select `python` stack. Everything default.
2. The `amplify push` gives me this error
```bash
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
cies(best_match):
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 275, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 174, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 193, in get_legacy_dependencies
    dist = ireq.get_dist()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 1069, in get_dist
    egg_info = self.egg_info_path('').rstrip('/')
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 514, in egg_info_path
    raise InstallationError(
pip9.exceptions.InstallationError: No files/directories in /something/webapp/amplify/backend/function/getUploadedFiles/src (from )
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Command failed with exit code 1: pipenv install
```
Not sure what the story is?

### Expected behavior

To just deploy the functions

### Reproduction steps

As above.

Also:
Python 3.8.10
pipenv, version 11.9.0

webapp/amplify/backend/function/getUploadedFiles/Pipfile:
```ini
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
src = {editable = true, path = "./src"}

[requires]
python_version = "3.8"
```

webapp/amplify/backend/function/getUploadedFiles/src/setup.py:
```python
from distutils.core import setup

setup(name='src', version='1.0')
```
I note that when i 
```
cd webapp/amplify/backend/function/getUploadedFiles
pipenv install
```
I get the same error. 

When i try (from that dir)
```bash
pipenv run install -e src/
```
I get 
```
Obtaining file:///something/webapp/amplify/backend/function/getUploadedFiles/src
Installing collected packages: src
  Attempting uninstall: src
    Found existing installation: src 1.0
ERROR: Cannot uninstall 'src'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
Then `pipenv install` works but with the same error as above thus `amplify push` still doesn't work?

So looks like there is something wrong with the default pipenv setup?

### GraphQL schema(s)

None

### Log output

None

### Additional information

None

**Comment by awhillas** [comment]
Seems to work when i remove the 
```
src = {editable = true, path = "./src"}
```
line in the Pipfile? The lambda seems to still work so I'm not sure why you have that in there since you copy all the files anyway?
Also, when setting up a trigger from an s3 bucket there is no choice between Nodejs and Python?
I'm getting the impression that python was an afterthought...

**Comment by awhillas** [comment]
Also, I'm getting this error when the CI tries to build the project
```
2022-03-10T03:43:18.568Z [INFO]: python3 found but version Python 3.7.10 is less than the minimum required version.
                                 You must have python >= 3.8 installed and available on your PATH as "python3" or "python". It can be installed from https://www.python.org/downloads
                                 You must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".
                                 You must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".
```
Wrong version of python?!

**Comment by josefaidt** [comment]
Hey @awhillas :wave: thanks for raising this! For the hosting pipeline issue regarding the Python version, I'm checking to see if there's an easier way to re-map the python3 binary but for the mean time it appears folks have been able to successfully use later versions of python by modifying the buildspec (`amplify.yml`)
https://github.com/aws-amplify/amplify-hosting/issues/595#issuecomment-761049327

For the pipfile line, I wasn't able to reproduce the issue with the default python template in Windows with WSL, however I will investigate this further

**Comment by awhillas** [comment]
thanks @josefaidt I rebuilt the project from scratch and it seems to have righted itself. I;ll have a look into the build spec. Thanks!

**Comment by awhillas** [comment]
@josefaidt I seem to be getting this error again. Steps:
```
amplify add function
```
Choose the python option with all the defaults.
I then want to add a dependency so I
```
cd amplify/backend/functions/newFunction
pipenv shell
pipenv install wheel setuptools
```
then i get the error
```
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
encies(best_match):
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 275, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 174, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 193, in get_legacy_dependencies
    dist = ireq.get_dist()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 1069, in get_dist
    egg_info = self.egg_info_path('').rstrip('/')
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 514, in egg_info_path
    raise InstallationError(
pip9.exceptions.InstallationError: No files/directories in /dev/amplify/backend/function/newFunction/src (from )
```
I'm assuming this has something to do with the default python function setup.py? There is [an issue](https://github.com/pypa/pipenv/issues/1744) on pipenv project about it.

What is the official way to install dependencies in python lambda functions? Is it possible to just specify a `requirements.txt` file instead?

**Comment by awhillas** [comment]
Actually, i think i fixed it. It was because i used `sudo apt install pipenv`. I uninstalled and did `pip3 install --user pipenv` and it seems to work now!
Sorry for the trouble

**Comment by mcnamara-charles** [comment]
I'm still having issues on auto deploy with CI/CD. It gets through most of the backend build steps but then it gets to `pipenv install` and it fails. I'm using Python 3.11 and my build settings file looks like:
```
version: 1
backend:
  phases:
    preBuild:
      commands:
        - export BASE_PATH=$(pwd)
        - yum install -y gcc openssl-devel bzip2-devel libffi-devel python3.11-pip
        - cd /opt && wget https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tgz
        - cd /opt && tar xzf Python-3.11.1.tgz
        - cd /opt/Python-3.11.1 && ./configure --enable-optimizations
        - cd /opt/Python-3.11.1 && make altinstall
        - pip3.8 install --user pipenv
        - ln -fs /usr/local/bin/python3.11 /usr/bin/python3
        - ln -fs /usr/local/bin/pip3.11 /usr/bin/pip3
        - cd $BASE_PATH
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by LeoReubelt** [comment]
I am having a similar problem. I create a python function. And when I try to push, mock, or cd to the function path and run pipenv install, i get the following.... 

FileNotFoundError: [Errno 2] No such file or directory: '/Users/leo/.local/share/virtualenvs/testFunction-asdhjdy/bin/python'
🛑 Command failed with exit code 1: pipenv install

I have uninstalled and re-installed pipenv as discussed above. I've deleted and recreated the function. Always the same.

**Comment by Celinesco** [comment]
Is there any update on this?

**Comment by arnab-m** [comment]
> Actually, i think i fixed it. It was because i used `sudo apt install pipenv`. I uninstalled and did `pip3 install --user pipenv` and it seems to work now! Sorry for the trouble

Even if I do this I got this following issue in latest amplify build:
```
2023-06-28T19:44:07.321Z [WARNING]: ✔ Initialized provider successfully.
2023-06-28T19:44:10.412Z [WARNING]: Creating a virtualenv for this project...
2023-06-28T19:44:10.423Z [WARNING]: Pipfile: /codebuild/output/src806185043/src/beveredge/amplify/backend/function/credentialsLambda/Pipfile
2023-06-28T19:44:10.427Z [WARNING]: Using /usr/local/bin/python3.8 (3.8.2) to create virtualenv...
2023-06-28T19:44:11.053Z [WARNING]: created virtual environment CPython3.8.2.final.0-64 in 431ms
                                    creator CPython3Posix(dest=/root/.local/share/virtualenvs/credentialsLambda-m7KrhyLo, clear=False, no_vcs_ignore=False, global=False)
                                    seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
                                    added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
                                    activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
2023-06-28T19:44:11.059Z [WARNING]: ✔ Successfully created virtual environment!
2023-06-28T19:44:11.106Z [WARNING]: Virtualenv location: /root/.local/share/virtualenvs/credentialsLambda-m7KrhyLo
2023-06-28T19:44:11.147Z [INFO]: Installing dependencies from Pipfile.lock (e02f68)...
2023-06-28T19:44:12.066Z [WARNING]: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
                                    or: setup.py --help [cmd1 cmd2 ...]
                                    or: setup.py --help-commands
                                    or: setup.py cmd --help
                                    error: invalid command 'egg_info'
2023-06-28T19:44:12.186Z [WARNING]: ✖ There was an error initializing your environment.
2023-06-28T19:44:12.187Z [INFO]: 🛑 Failed to install dependencies in /codebuild/output/src806185043/src/beveredge/amplify/backend/function/credentialsLambda: Error: Command failed with exit code 1: pipenv install
2023-06-28T19:44:12.187Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-06-28T19:44:12.200Z [INFO]: 
2023-06-28T19:44:12.201Z [INFO]: Session Identifier: fe85c88b-4222-4b58-9a10-7fa748db6afb
2023-06-28T19:44:12.238Z [ERROR]: !!! Build failed
2023-06-28T19:44:12.238Z [ERROR]: !!! Non-Zero Exit Code detected
2023-06-28T19:44:12.239Z [INFO]: # Starting environment caching...
2023-06-28T19:44:12.240Z [INFO]: # Uploading environment cache artifact...
2023-06-28T19:44:12.311Z [INFO]: # Uploaded environment cache artifact
2023-06-28T19:44:12.311Z [INFO]: # Environment caching completed
Terminating logging...
```

I have this amplify.yml file:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
backend:
  phases:
    preBuild:
      commands:
        - export BASE_PATH=$(pwd)
        - yum install -y gcc openssl-devel bzip2-devel libffi-devel python3.8-pip
        - cd /opt && wget https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz
        - cd /opt && tar xzf Python-3.8.2.tgz 
        - cd /opt/Python-3.8.2 && ./configure --enable-optimizations
        - cd /opt/Python-3.8.2 && make altinstall
        - pip3.8 install --user pipenv
        - pip3.8 install --upgrade setuptools
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - cd $BASE_PATH
    build:
      commands:
        - "# Execute Amplify CLI with the helper script"
        - amplifyPush --simple
```

**Comment by esteban-serfe** [comment]
I've just had this issue when trying to add a dependency to an an existing lambda editing the Pipfile. In my case could not trigger the mock of the function locally.

After getting arround thinking that the problem was my docker setup for this, found out that the problem is the auto-generated setup.py file which is not compatible with pipenv and wheel problem (python 3.8 in my case).

for the ones that know python more than me, the previous error is easy, but was not my case. In my case had to dig up the documentation to find out how the "src-layout" was supposed to work.

To solve this I've set the setup.py file

```
from setuptools import setup, find_packages

setup(
    name='src',
    version='1.0',
    packages=find_packages(where="src", exclude="index")
)
```
and violá... issue fixed!

Hope this prevent someone else the trouble of hours frustration.

**Comment by arnab-m** [comment]
> I've just had this issue when trying to add a dependency to an an existing lambda editing the Pipfile. In my case could not trigger the mock of the function locally.
> 
> After getting arround thinking that the problem was my docker setup for this, found out that the problem is the auto-generated setup.py file which is not compatible with pipenv and wheel problem (python 3.8 in my case).
> 
> for the ones that know python more than me, the previous error is easy, but was not my case. In my case had to dig up the documentation to find out how the "src-layout" was supposed to work.
> 
> To solve this I've set the setup.py file
> 
> ```
> from setuptools import setup, find_packages
> 
> setup(
>     name='src',
>     version='1.0',
>     packages=find_packages(where="src", exclude="index")
> )
> ```
> 
> and violá... issue fixed!
> 
> Hope this prevent someone else the trouble of hours frustration.
> 
> Might be that with this issue we got a better messaging next time: [pypa/pipenv#5155](https://github.com/pypa/pipenv/issues/5155)

Thanks a lot, @esteban-serfe ! It fixed the issue.

**Comment by arnab-m** [comment]
Thanks a lot, @esteban-serfe ! It fixed the github CI/CD issue and successfully deployed the app in amplify cloud. But now, I ran into a new problem while I am trying to execute `amplify push` command from my local:
```
ERROR: Couldn't install package: [Requirement(_name='src', vcs=None, req=FileRequirement(setup_path=None, path='./src', editable=True, extras=None, _uri_scheme='path', uri='file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src', link=<Link file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src>, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=SetupInfo(name='src', base_dir='C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src', _version='1.0', _requirements=frozenset(), build_requires=(), build_backend='setuptools.build_meta:__legacy__', setup_requires=(), python_requires=None, _extras_requirements=(), setup_cfg=WindowsPath('C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src/setup.cfg'), setup_py=WindowsPath('C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src/setup.py'), pyproject=WindowsPath('C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src/pyproject.toml'), ireq=<InstallRequirement object: src==1.0@ file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src from file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src editable=True>, extra_kwargs={'build_dir': 'C:\\Users\\SALAMU~1\\AppData\\Local\\Temp\\reqlib-builde_y78rkk', 'src_dir': 'C:\\Users\\SALAMU~1\\AppData\\Local\\Temp\\reqlib-srccnp7pkgy', 'download_dir': 'C:\\Users\\Salam Uddin\\AppData\\Local\\pipenv\\pipenv\\Cache\\pkgs', 'wheel_download_dir': 'C:\\Users\\Salam Uddin\\AppData\\Local\\pipenv\\pipenv\\Cache\\wheels'}, metadata=None, stack=<contextlib.ExitStack object at 0x000002EADD23A820>, _finalizer=<finalize object at 0x2eadd2a16e0; for 'SetupInfo' at 0x2eadd2b1f60>), _has_hashed_name=False, _parsed_line=<Line (editable=True, name=src, path=C:/Users/Salam Uddin/Documents/Smart Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, uri=file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, name='src', req=Requirement.parse('src@ file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src')), markers=None, _specifiers='', index=None, editable=True, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=True, name=src, path=C:/Users/Salam Uddin/Documents/Smart Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, uri=file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None), Requirement(_name='src', vcs=None, req=FileRequirement(setup_path=None, path='./src', editable=True, extras=None, _uri_scheme='path', uri='file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src', link=<Link file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src>, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=SetupInfo(name='src', base_dir='C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src', _version='1.0', _requirements=frozenset(), build_requires=(), build_backend='setuptools.build_meta:__legacy__', setup_requires=(), python_requires=None, _extras_requirements=(), setup_cfg=WindowsPath('C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src/setup.cfg'), setup_py=WindowsPath('C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src/setup.py'), pyproject=WindowsPath('C:/users/salam uddin/documents/smart container/github/beveredge/amplify/backend/function/setparamslambda/src/pyproject.toml'), ireq=<InstallRequirement object: src==1.0@ file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src from file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src editable=True>, extra_kwargs={'build_dir': 'C:\\Users\\SALAMU~1\\AppData\\Local\\Temp\\reqlib-builde_y78rkk', 'src_dir': 'C:\\Users\\SALAMU~1\\AppData\\Local\\Temp\\reqlib-srccnp7pkgy', 'download_dir': 'C:\\Users\\Salam Uddin\\AppData\\Local\\pipenv\\pipenv\\Cache\\pkgs', 'wheel_download_dir': 'C:\\Users\\Salam Uddin\\AppData\\Local\\pipenv\\pipenv\\Cache\\wheels'}, metadata=None, stack=<contextlib.ExitStack object at 0x000002EADD23A820>, _finalizer=<finalize object at 0x2eadd2a16e0; for 'SetupInfo' at 0x2eadd2b1f60>), _has_hashed_name=False, _parsed_line=<Line (editable=True, name=src, path=C:/Users/Salam Uddin/Documents/Smart Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, uri=file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, name='src', req=Requirement.parse('src@ file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src')), markers=None, _specifiers='', index=None, editable=True, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=True, name=src, path=C:/Users/Salam Uddin/Documents/Smart Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, uri=file:///C:/Users/Salam%20Uddin/Documents/Smart%20Container/GITHUB/beveredge/amplify/backend/function/setparamsLambda/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None)]
 Package installation failed...
🛑 Failed to install dependencies in C:\Users\Salam Uddin\Documents\Smart Container\GITHUB\beveredge\amplify\backend\function\setparamsLambda: Error: Command failed with exit code 1: pipenv install
```
Before fixing the deploy issue with your solution, `amplify push` command was working fine in my local.

**Comment by esteban-serfe** [comment]
Unfortunately my knowhow on python on windows is limited. Sounds like the src dependency is not been able to be installed. Is that the first or the last dependency on the packages section?

Usually I delete the virtualenv for that labda and the install process start again without issue.
Sorry for not been able to help more here, but will be nice to have your solution in this case (if you find it)

**Comment by arnab-m** [comment]
> Unfortunately my knowhow on python on windows is limited. Sounds like the src dependency is not been able to be installed. Is that the first or the last dependency on the packages section?
> 
> Usually I delete the virtualenv for that labda and the install process start again without issue. Sorry for not been able to help more here, but will be nice to have your solution in this case (if you find it)

Sure, thanks for your input anyway. src dependency is the last in the packages section.

**Comment by arnab-m** [comment]
Hi @esteban-serfe , the local python issue is solved now. I just reinstalled the pipenv `pip3 install --user pipenv` in my root App directory.

**Comment by femmedecentral** [comment]
FWIW, I came searching for this error message. I was able to resolve just by doing an amplify pull. Making changes and then my amplify push succeeded afterwards.

**Comment by femmedecentral** [comment]
I also got a pipenv problem again; just to record, the exact issue was:

FileNotFoundError: [Errno 2] No such file or directory: '[path]/[lambda_function_virtual_env]/bin/python'
🛑 Failed to install dependencies in [path_to_root]/amplify/backend/function/[lambda_function_name]: Error: Command failed with exit code 1: pipenv install

but the amplify pull and then push didn't work this time. My steps to resolve this time were:
cd [path_to_root]/amplify/backend/function/[lambda_function_name]
pipenv --rm
pipenv install 
(then I got an error about a version of Python wasn't installed, so I did brew install python@[version#])
pipenv --python /usr/local/opt/python@[version#]/bin/python[version#] install
cd [path_to_root]
amplify push

not sure how this all happened, but hopefully someone else might find this useful.

**Comment by si3mshady** [comment]
fucking disgracful how AWS support does not do anything with this shitty python support, I recommend posting these issues on Linkedin and tagging AWS

**Comment by stratiform** [comment]
For those still tortured by errors like this and stuck waiting for Gen 2 migration tools, I've been able to successfully upgrade my existing python 3.8 runtimes to python 3.11 on AL2023, incorporating some of the above methods - see this comment: 
https://github.com/aws-amplify/amplify-cli/issues/13733#issuecomment-2448852712

Related PSA - python 3.8 lambda runtimes (despite them begin default for amplify gen 1 lambda functions) are deprecated on AWS, which is the reason we were forced to migrate 😢

**Comment by yakovsushenok** [comment]
The problem for me was that I had python 3.12 installed locally but 3.10 specified in the PipFile, so when I changed it to 3.12 my amplify push command worked.
